# Generated by Django 2.2 on 2021-09-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
