# Generated by Django 2.2 on 2021-11-09 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanduel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='entries_url',
            field=models.URLField(blank=True, help_text='https://api.fanduel.com/contests/63955-248463555/entries', null=True),
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_url', models.URLField(help_text='https://api.fanduel.com/entries/2632507443')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_json', models.TextField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fanduel.Contest')),
            ],
        ),
    ]
