# Generated by Django 2.2 on 2021-11-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanduel', '0003_contestentry_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='num_entries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='url',
            field=models.URLField(blank=True, help_text='https://api.fanduel.com/contests/63955-248463555', null=True),
        ),
    ]
