# Generated by Django 2.2 on 2021-11-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanduel', '0006_contest_contest_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='last_page_processed',
            field=models.IntegerField(default=0),
        ),
    ]
