# Generated by Django 2.2 on 2021-11-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanduel', '0008_auto_20211123_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_main_slate',
            field=models.BooleanField(default=True),
        ),
    ]
