# Generated by Django 2.2 on 2022-02-11 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slate',
            options={'ordering': ['-week__slate_year', '-week__num']},
        ),
        migrations.RemoveField(
            model_name='slate',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='slate',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='slate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='slateplayer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='slateplayer',
            name='slate_game',
        ),
        migrations.AddField(
            model_name='slate',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slates', to='nfl_sd.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slate',
            name='game_sim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SlateGame',
        ),
    ]
