# Generated by Django 2.2 on 2022-02-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0002_auto_20220211_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slate',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slates', to='nfl_sd.Game'),
        ),
    ]
