# Generated by Django 2.2 on 2022-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0003_auto_20220211_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayer',
            name='roster_position',
            field=models.CharField(default='FLEX', max_length=5),
        ),
    ]
