# Generated by Django 2.2 on 2022-02-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0004_slateplayer_roster_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateplayer',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slateplayer',
            name='site_pos',
            field=models.CharField(default='QB', max_length=5),
        ),
        migrations.AlterField(
            model_name='slateplayer',
            name='team',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
