# Generated by Django 2.2 on 2022-02-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0005_auto_20220211_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetcolumnheaders',
            name='column_captain_ownership',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
