# Generated by Django 2.2 on 2022-02-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0006_sheetcolumnheaders_column_captain_ownership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slateplayerprojection',
            old_name='cpt_ownership_projection',
            new_name='ownership_rojection',
        ),
        migrations.RenameField(
            model_name='slateplayerrawprojection',
            old_name='cpt_ownership_projection',
            new_name='ownership_rojection',
        ),
        migrations.RemoveField(
            model_name='slateplayerprojection',
            name='flex_ownership_projection',
        ),
        migrations.RemoveField(
            model_name='slateplayerrawprojection',
            name='flex_ownership_projection',
        ),
    ]
