# Generated by Django 2.2 on 2022-02-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0007_auto_20220211_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slateplayerprojection',
            old_name='ownership_rojection',
            new_name='ownership_projection',
        ),
    ]
