# Generated by Django 2.2 on 2022-02-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0010_auto_20220211_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildplayerprojection',
            old_name='cpt_ownership_projection',
            new_name='ownership_projection',
        ),
        migrations.RemoveField(
            model_name='buildplayerprojection',
            name='adjusted_opportunity',
        ),
        migrations.RemoveField(
            model_name='buildplayerprojection',
            name='balanced_projection',
        ),
        migrations.RemoveField(
            model_name='buildplayerprojection',
            name='balanced_value',
        ),
        migrations.RemoveField(
            model_name='buildplayerprojection',
            name='flex_ownership_projection',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='binked',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='construction_ready',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='great_build',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='in_play_criteria',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='optimals_pct_complete',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='top_score',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='total_cashes',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='total_half_pct',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='total_one_pct',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='total_optimals',
        ),
    ]
