# Generated by Django 2.2 on 2022-02-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0011_auto_20220211_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildlineup',
            name='duplicated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='ownership_projection',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
