# Generated by Django 2.2 on 2022-02-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_sd', '0012_auto_20220211_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='num_contest_entries',
            field=models.IntegerField(default=10000),
        ),
    ]
