# Generated by Django 2.2 on 2022-03-16 11:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dk_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fd_name', models.CharField(blank=True, max_length=255, null=True)),
                ('f1_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Alias',
                'verbose_name_plural': 'Aliases',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('badge', models.CharField(max_length=5, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('team', models.CharField(max_length=100, null=True)),
                ('driver_image', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('race_season', models.IntegerField(default=2022)),
                ('race_name', models.CharField(max_length=255, null=True)),
                ('race_date', models.DateTimeField(null=True)),
                ('qualifying_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_distance', models.IntegerField(default=0)),
                ('scheduled_laps', models.IntegerField(default=0)),
                ('num_cars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RaceSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iterations', models.IntegerField(default=10000)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='uploads/sim_input_files')),
                ('dk_salaries', models.FileField(blank=True, null=True, upload_to='uploads/dk_salaries')),
                ('ll_mean', models.IntegerField(default=1)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sims', to='formula_1.Race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceSimLapsLedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_rank', models.IntegerField(default=1)),
                ('pct_laps_led_min', models.FloatField(default=0.0)),
                ('pct_laps_led_max', models.FloatField(default=0.0)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ll_profiles', to='formula_1.RaceSim')),
            ],
        ),
        migrations.CreateModel(
            name='RaceSimFastestLapsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_rank', models.IntegerField(default=1)),
                ('probability', models.FloatField(default=0.0)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fl_profiles', to='formula_1.RaceSim')),
            ],
        ),
        migrations.CreateModel(
            name='RaceSimDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dk_salary', models.IntegerField(default=0)),
                ('starting_position', models.IntegerField(default=0)),
                ('speed_min', models.IntegerField(default=1)),
                ('speed_max', models.IntegerField(default=5)),
                ('incident_rate', models.FloatField(default=0.0)),
                ('pct_laps_led_min', models.FloatField(default=0.0)),
                ('pct_laps_led_max', models.FloatField(default=0.0)),
                ('q_outcomes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None)),
                ('fp_outcomes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None)),
                ('ll_outcomes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None)),
                ('fl_outcomes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None)),
                ('incident_outcomes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5, null=True), blank=True, null=True, size=None)),
                ('avg_fp', models.FloatField(default=0.0)),
                ('avg_ll', models.FloatField(default=0.0)),
                ('gto', models.FloatField(default=0.0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='formula_1.Driver')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='formula_1.RaceSim')),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishing_position', models.IntegerField(default=0)),
                ('starting_position', models.IntegerField(default=0)),
                ('laps_led', models.IntegerField(default=0)),
                ('laps_completed', models.IntegerField(default=0)),
                ('finishing_status', models.CharField(default='Running', max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='formula_1.Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='formula_1.Race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceDriverLap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField(default=0)),
                ('lap_time', models.FloatField(blank=True, null=True)),
                ('lap_speed', models.FloatField(blank=True, null=True)),
                ('running_pos', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_laps', to='formula_1.Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_laps', to='formula_1.Race')),
            ],
        ),
        migrations.CreateModel(
            name='MissingAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel')], default='draftkings', max_length=50)),
                ('alias_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_1', to='formula_1.Alias')),
                ('alias_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_2', to='formula_1.Alias')),
                ('alias_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_3', to='formula_1.Alias')),
            ],
            options={
                'verbose_name': 'Missing Alias',
                'verbose_name_plural': 'Missing Aliases',
            },
        ),
    ]
