# Generated by Django 2.2 on 2022-03-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_image',
        ),
    ]
