# Generated by Django 2.2 on 2022-03-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0002_remove_driver_driver_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='dk_salary_cpt',
            field=models.IntegerField(default=0),
        ),
    ]
