# Generated by Django 2.2 on 2022-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0004_remove_racesimdriver_q_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.BigIntegerField(auto_created=True, blank=True, primary_key=True, serialize=False),
        ),
    ]
