# Generated by Django 2.2 on 2022-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0006_remove_driver_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
