# Generated by Django 2.2 on 2022-03-18 10:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0007_auto_20220317_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='dk_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
