# Generated by Django 2.2 on 2022-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0009_racesimdriver_avg_dk_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesimdriver',
            name='dk_salary_cpt',
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='dk_position',
            field=models.CharField(choices=[('D', 'D'), ('CPT', 'CPT'), ('CNSTR', 'CNSTR')], default='D', max_length=10),
        ),
    ]
