# Generated by Django 2.2 on 2022-03-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0012_driver_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='formula_1.Constructor'),
        ),
        migrations.AlterField(
            model_name='racesimdriver',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='formula_1.Driver'),
        ),
    ]
