# Generated by Django 2.2 on 2022-03-22 10:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0013_auto_20220318_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSimLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('median', models.FloatField(db_index=True, default=0.0)),
                ('s75', models.FloatField(db_index=True, default=0.0)),
                ('s90', models.FloatField(db_index=True, default=0.0)),
                ('count', models.IntegerField(db_index=True, default=1)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_constructor', to='formula_1.RaceSimDriver')),
                ('cpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_cpt', to='formula_1.RaceSimDriver')),
                ('flex_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_flex_1', to='formula_1.RaceSimDriver')),
                ('flex_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_flex_2', to='formula_1.RaceSimDriver')),
                ('flex_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_flex_3', to='formula_1.RaceSimDriver')),
                ('flex_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_flex_4', to='formula_1.RaceSimDriver')),
                ('sim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sims', to='formula_1.RaceSim')),
            ],
            options={
                'verbose_name': 'Optimal Lineup',
                'verbose_name_plural': 'Optimal Lineups',
                'ordering': ['-count'],
            },
        ),
    ]
