# Generated by Django 2.2 on 2022-03-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0015_auto_20220322_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesimlineup',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='formula_1.RaceSim'),
        ),
    ]
