# Generated by Django 2.2 on 2022-03-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0017_racesimnumleadersprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=255, verbose_name='Slate')),
                ('site', models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel')], default='draftkings', max_length=50)),
                ('salaries', models.FileField(blank=True, null=True, upload_to='uploads/salaries')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slates', to='formula_1.Race')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='SlatePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slate_player_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('D', 'D'), ('CPT', 'CPT'), ('CNSTR', 'CNSTR')], default='D', max_length=10)),
                ('salary', models.IntegerField()),
                ('fantasy_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ownership', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slates', to='formula_1.Constructor')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slates', to='formula_1.Driver')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='formula_1.Slate')),
            ],
            options={
                'ordering': ['-salary', 'name'],
            },
        ),
    ]
