# Generated by Django 2.2 on 2022-03-23 12:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0018_slate_slateplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPlayerProjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_position', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('projection', models.FloatField(db_index=True, default=0.0, verbose_name='Proj')),
                ('ceiling', models.FloatField(db_index=True, default=0.0, verbose_name='Ceil')),
                ('s75', models.FloatField(db_index=True, default=0.0, verbose_name='s75')),
                ('in_play', models.BooleanField(default=True)),
                ('op', models.FloatField(default=0.0)),
                ('gto', models.FloatField(default=0.0)),
                ('min_exposure', models.FloatField(default=0.0, verbose_name='min')),
                ('max_exposure', models.FloatField(default=1.0, verbose_name='max')),
            ],
            options={
                'verbose_name': 'Player Projection',
                'verbose_name_plural': 'Player Projections',
                'ordering': ['-slate_player__salary'],
            },
        ),
        migrations.CreateModel(
            name='SlateBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('used_in_contests', models.BooleanField(default=False, verbose_name='Used')),
                ('total_lineups', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('max_entrants', models.PositiveIntegerField(default=50000, verbose_name='max_entrants')),
            ],
            options={
                'verbose_name': 'Slate Build',
                'verbose_name_plural': 'Slate Builds',
            },
        ),
        migrations.CreateModel(
            name='SlateBuildConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel')], default='draftkings', max_length=50)),
                ('randomness', models.DecimalField(decimal_places=2, default=0.75, max_digits=2)),
                ('uniques', models.IntegerField(default=1)),
                ('min_salary', models.IntegerField(default=0)),
                ('optimize_by_percentile', models.IntegerField(default=50)),
                ('lineup_multiplier', models.IntegerField(default=1)),
                ('clean_by_percentile', models.IntegerField(default=50)),
                ('duplicate_threshold', models.FloatField(default=5)),
            ],
            options={
                'verbose_name': 'Build Config',
                'verbose_name_plural': 'Build Configs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SlateBuildGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_from_group', models.PositiveIntegerField(default=1)),
                ('min_from_group', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='formula_1.SlateBuild')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineups_as_constructor', to='formula_1.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='cpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineups_as_cpt', to='formula_1.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='flex_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineups_as_flex_1', to='formula_1.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='flex_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineups_as_flex_2', to='formula_1.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='flex_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineups_as_flex_3', to='formula_1.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='flex_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineups_as_flex_4', to='formula_1.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineups', to='formula_1.RaceSim'),
        ),
        migrations.CreateModel(
            name='SlateBuildLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('ownership_projection', models.DecimalField(decimal_places=9, default=0.0, max_digits=10)),
                ('duplicated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('roi', models.FloatField(db_index=True, default=0.0)),
                ('median', models.FloatField(db_index=True, default=0.0)),
                ('s75', models.FloatField(db_index=True, default=0.0)),
                ('s90', models.FloatField(db_index=True, default=0.0)),
                ('sort_proj', models.FloatField(db_index=True, default=0.0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='formula_1.SlateBuild', verbose_name='Build')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_constructor', to='formula_1.BuildPlayerProjection')),
                ('cpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_cpt', to='formula_1.BuildPlayerProjection')),
                ('flex_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_flex_1', to='formula_1.BuildPlayerProjection')),
                ('flex_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_flex_2', to='formula_1.BuildPlayerProjection')),
                ('flex_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_flex_3', to='formula_1.BuildPlayerProjection')),
                ('flex_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups_as_flex_4', to='formula_1.BuildPlayerProjection')),
            ],
            options={
                'verbose_name': 'Lineup',
                'verbose_name_plural': 'Lineups',
                'ordering': ['-sort_proj'],
            },
        ),
        migrations.CreateModel(
            name='SlateBuildGroupPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='formula_1.SlateBuildGroup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='formula_1.BuildPlayerProjection')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.AddField(
            model_name='slatebuild',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='formula_1.SlateBuildConfig', verbose_name='Config'),
        ),
        migrations.AddField(
            model_name='slatebuild',
            name='sim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='formula_1.RaceSim'),
        ),
        migrations.AddField(
            model_name='slatebuild',
            name='slate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='formula_1.Slate'),
        ),
        migrations.AddField(
            model_name='buildplayerprojection',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='formula_1.SlateBuild', verbose_name='Build'),
        ),
        migrations.AddField(
            model_name='buildplayerprojection',
            name='slate_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='formula_1.SlatePlayer'),
        ),
    ]
