# Generated by Django 2.2 on 2022-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0022_auto_20220425_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesim',
            name='optimal_lineups_per_iteration',
            field=models.IntegerField(default=1, verbose_name='# GTO Lineups'),
        ),
    ]
