# Generated by Django 2.2 on 2022-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_1', '0023_auto_20220426_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesim',
            name='for_backtest',
            field=models.BooleanField(default=False),
        ),
    ]
