# Generated by Django 2.2 on 2022-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='nascar_driver_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
