# Generated by Django 2.2 on 2022-01-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0003_race_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
