# Generated by Django 2.2 on 2022-01-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0006_auto_20220125_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='driver',
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nascar_driver_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
