# Generated by Django 2.2 on 2022-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0008_raceresult_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
