# Generated by Django 2.2 on 2022-01-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0010_racecautionsegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceInfraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField(default=0)),
                ('lap_assessed', models.IntegerField(default=0)),
                ('infraction', models.TextField(blank=True, null=True)),
                ('penalty', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='nascar.Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='nascar.Race')),
            ],
        ),
    ]
