# Generated by Django 2.2 on 2022-01-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0012_auto_20220126_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceDriverLap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField(default=0)),
                ('lap_time', models.FloatField(blank=True, null=True)),
                ('lap_speed', models.FloatField(blank=True, null=True)),
                ('running_pos', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_laps', to='nascar.Driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_laps', to='nascar.Race')),
            ],
        ),
    ]
