# Generated by Django 2.2 on 2022-01-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0014_racesim_racesimdriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesim',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sim_input_files'),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='best_fp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='crash_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='infraction_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='mech_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='worst_fp',
            field=models.IntegerField(default=0),
        ),
    ]
