# Generated by Django 2.2 on 2022-01-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0016_auto_20220128_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='starting_position',
            field=models.IntegerField(default=0),
        ),
    ]
