# Generated by Django 2.2 on 2022-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0018_auto_20220131_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='early_stage_caution_mean',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AddField(
            model_name='track',
            name='early_stage_caution_prob_accident_major',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='track',
            name='early_stage_caution_prob_accident_medium',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='track',
            name='early_stage_caution_prob_accident_small',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='track',
            name='early_stage_caution_prob_debris',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='track',
            name='final_stage_caution_mean',
            field=models.IntegerField(default=3.0),
        ),
        migrations.AddField(
            model_name='track',
            name='final_stage_caution_prob_accident_major',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='track',
            name='final_stage_caution_prob_accident_medium',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='track',
            name='final_stage_caution_prob_accident_small',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='track',
            name='final_stage_caution_prob_debris',
            field=models.FloatField(default=0.1),
        ),
    ]
