# Generated by Django 2.2 on 2022-02-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0019_auto_20220201_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='early_stage_caution_mean',
        ),
        migrations.RemoveField(
            model_name='track',
            name='early_stage_caution_prob_accident_major',
        ),
        migrations.RemoveField(
            model_name='track',
            name='early_stage_caution_prob_accident_medium',
        ),
        migrations.RemoveField(
            model_name='track',
            name='early_stage_caution_prob_accident_small',
        ),
        migrations.RemoveField(
            model_name='track',
            name='early_stage_caution_prob_debris',
        ),
        migrations.RemoveField(
            model_name='track',
            name='final_stage_caution_mean',
        ),
        migrations.RemoveField(
            model_name='track',
            name='final_stage_caution_prob_accident_major',
        ),
        migrations.RemoveField(
            model_name='track',
            name='final_stage_caution_prob_accident_medium',
        ),
        migrations.RemoveField(
            model_name='track',
            name='final_stage_caution_prob_accident_small',
        ),
        migrations.RemoveField(
            model_name='track',
            name='final_stage_caution_prob_debris',
        ),
        migrations.AddField(
            model_name='racesim',
            name='early_stage_caution_mean',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AddField(
            model_name='racesim',
            name='early_stage_caution_prob_accident_major',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='racesim',
            name='early_stage_caution_prob_accident_medium',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='racesim',
            name='early_stage_caution_prob_accident_small',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='racesim',
            name='early_stage_caution_prob_debris',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='racesim',
            name='final_stage_caution_mean',
            field=models.IntegerField(default=3.0),
        ),
        migrations.AddField(
            model_name='racesim',
            name='final_stage_caution_prob_accident_major',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='racesim',
            name='final_stage_caution_prob_accident_medium',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='racesim',
            name='final_stage_caution_prob_accident_small',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='racesim',
            name='final_stage_caution_prob_debris',
            field=models.FloatField(default=0.1),
        ),
    ]
