# Generated by Django 2.2 on 2022-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0020_auto_20220201_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesim',
            name='early_stage_caution_mean',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='racesim',
            name='final_stage_caution_mean',
            field=models.FloatField(default=3.0),
        ),
    ]
