# Generated by Django 2.2 on 2022-02-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0022_racesimdamageprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdamageprofile',
            name='name',
            field=models.CharField(default='Small Accident', max_length=100),
        ),
    ]
