# Generated by Django 2.2 on 2022-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0023_racesimdamageprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesimdamageprofile',
            name='max_cars_involved',
            field=models.IntegerField(default=0),
        ),
    ]
