# Generated by Django 2.2 on 2022-02-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0024_auto_20220202_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSimPenaltyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('is_green', models.BooleanField(default=False)),
                ('floor_impact', models.FloatField(default=0.0)),
                ('ceiling_impact', models.FloatField(default=0.0)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_profiles', to='nascar.RaceSim')),
            ],
        ),
    ]
