# Generated by Django 2.2 on 2022-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0025_racesimpenaltyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesimpenaltyprofile',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
