# Generated by Django 2.2 on 2022-02-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0026_auto_20220204_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSimLapsLedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=0)),
                ('default_eligible_drivers', models.IntegerField(default=5)),
                ('per_caution_eligible_drivers', models.IntegerField(default=2)),
                ('max_eligible_drivers', models.IntegerField(default=2)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ll_profiles', to='nascar.RaceSim')),
            ],
        ),
    ]
