# Generated by Django 2.2 on 2022-02-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0027_racesimlapsledprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesim',
            name='track_variance',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='racesim',
            name='track_variance_late_restart',
            field=models.FloatField(default=0.1),
        ),
    ]
