# Generated by Django 2.2 on 2022-02-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0028_auto_20220216_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='team',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
