# Generated by Django 2.2 on 2022-02-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0030_racesimdriver_strategy_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesimdriver',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='driver',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
