# Generated by Django 2.2 on 2022-02-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0031_auto_20220216_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesimdriver',
            name='team',
        ),
    ]
