# Generated by Django 2.2 on 2022-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0032_remove_racesimdriver_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesimdriver',
            name='best_speed_rank',
        ),
        migrations.RemoveField(
            model_name='racesimdriver',
            name='worst_speed_rank',
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='best_possible_speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='speed_max',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='speed_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='worst_possible_speed',
            field=models.IntegerField(default=5),
        ),
    ]
