# Generated by Django 2.2 on 2022-02-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0033_auto_20220216_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='avg_fl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='avg_ll',
            field=models.FloatField(default=0.0),
        ),
    ]
