# Generated by Django 2.2 on 2022-02-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0034_auto_20220223_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='avg_fp',
            field=models.FloatField(default=0.0),
        ),
    ]
