# Generated by Django 2.2 on 2022-02-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0035_racesimdriver_avg_fp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSimFastestLapsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_laps_led_min', models.FloatField(default=0.0)),
                ('pct_laps_led_max', models.FloatField(default=1.0)),
                ('eligible_speed_min', models.IntegerField(default=1)),
                ('eligible_speed_max', models.IntegerField(default=1)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fl_profiles', to='nascar.RaceSim')),
            ],
        ),
    ]
