# Generated by Django 2.2 on 2022-02-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0036_racesimfastestlapsprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesim',
            name='laps_per_caution',
            field=models.FloatField(default=0.0),
        ),
    ]
