# Generated by Django 2.2 on 2022-02-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0038_slate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlatePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slate_player_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('fantasy_points', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ownership', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slates', to='nascar.Driver')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='nascar.Slate')),
            ],
            options={
                'ordering': ['-salary', 'name'],
            },
        ),
    ]
