# Generated by Django 2.2 on 2022-02-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0039_slateplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slates', to='nascar.Race'),
        ),
    ]
