# Generated by Django 2.2 on 2022-02-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0040_slate_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateBuildConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel')], default='draftkings', max_length=50)),
                ('randomness', models.DecimalField(decimal_places=2, default=0.75, max_digits=2)),
                ('uniques', models.IntegerField(default=1)),
                ('min_salary', models.IntegerField(default=0)),
                ('optimize_by_percentile', models.IntegerField(default=50)),
                ('lineup_multiplier', models.IntegerField(default=1)),
                ('clean_by_percentile', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Build Config',
                'verbose_name_plural': 'Build Configs',
                'ordering': ['id'],
            },
        ),
    ]
