# Generated by Django 2.2 on 2022-02-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0041_slatebuildconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('used_in_contests', models.BooleanField(default=False, verbose_name='Used')),
                ('total_lineups', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nascar.SlateBuildConfig', verbose_name='Config')),
                ('sim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nascar.RaceSim')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='nascar.Slate')),
            ],
            options={
                'verbose_name': 'Slate Build',
                'verbose_name_plural': 'Slate Builds',
            },
        ),
    ]
