# Generated by Django 2.2 on 2022-02-25 16:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0042_slatebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPlayerProjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=None)),
                ('projection', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Proj')),
                ('ceiling', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Ceil')),
                ('s75', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='s75')),
                ('in_play', models.BooleanField(default=True)),
                ('min_exposure', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='min')),
                ('max_exposure', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='max')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='nascar.SlateBuild', verbose_name='Build')),
                ('slate_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='nascar.SlatePlayer')),
            ],
            options={
                'verbose_name': 'Player Projection',
                'verbose_name_plural': 'Player Projections',
                'ordering': ['-slate_player__salary'],
            },
        ),
    ]
