# Generated by Django 2.2 on 2022-02-25 16:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0043_buildplayerprojection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateBuildLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=None)),
                ('roi', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10)),
                ('median', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10)),
                ('s75', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10)),
                ('s90', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='nascar.SlateBuild', verbose_name='Build')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_1', to='nascar.BuildPlayerProjection')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_2', to='nascar.BuildPlayerProjection')),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_3', to='nascar.BuildPlayerProjection')),
                ('player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_4', to='nascar.BuildPlayerProjection')),
                ('player_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_5', to='nascar.BuildPlayerProjection')),
                ('player_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_6', to='nascar.BuildPlayerProjection')),
            ],
            options={
                'verbose_name': 'Lineup',
                'verbose_name_plural': 'Lineups',
            },
        ),
    ]
