# Generated by Django 2.2 on 2022-02-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0044_slatebuildlineup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesimlapsledprofile',
            name='default_eligible_drivers',
        ),
        migrations.RemoveField(
            model_name='racesimlapsledprofile',
            name='max_eligible_drivers',
        ),
        migrations.RemoveField(
            model_name='racesimlapsledprofile',
            name='per_caution_eligible_drivers',
        ),
        migrations.RemoveField(
            model_name='racesimlapsledprofile',
            name='stage',
        ),
        migrations.AddField(
            model_name='racesimlapsledprofile',
            name='eligible_fl_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='racesimlapsledprofile',
            name='eligible_fl_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='racesimlapsledprofile',
            name='pct_laps_led_max',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='racesimlapsledprofile',
            name='pct_laps_led_min',
            field=models.FloatField(default=0.0),
        ),
    ]
