# Generated by Django 2.2 on 2022-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0045_auto_20220227_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplayerprojection',
            name='starting_position',
            field=models.IntegerField(default=0),
        ),
    ]
