# Generated by Django 2.2 on 2022-03-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0047_auto_20220301_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesim',
            name='dk_salaries',
            field=models.FileField(blank=True, null=True, upload_to='uploads/dk_salaries'),
        ),
        migrations.AddField(
            model_name='racesim',
            name='fd_salaries',
            field=models.FileField(blank=True, null=True, upload_to='uploads/fd_salaries'),
        ),
    ]
