# Generated by Django 2.2 on 2022-03-03 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0050_auto_20220302_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='median',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='roi',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='s75',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='s90',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='sim_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
