# Generated by Django 2.2 on 2022-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0052_auto_20220303_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildlineup',
            name='sort_proj',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
