# Generated by Django 2.2 on 2022-03-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0053_slatebuildlineup_sort_proj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slatebuildlineup',
            options={'ordering': ['-sort_proj'], 'verbose_name': 'Lineup', 'verbose_name_plural': 'Lineups'},
        ),
        migrations.RenameField(
            model_name='racesimlapsledprofile',
            old_name='eligible_fl_max',
            new_name='rank_order',
        ),
        migrations.RemoveField(
            model_name='racesimlapsledprofile',
            name='eligible_fl_min',
        ),
    ]
