# Generated by Django 2.2 on 2022-03-04 12:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0055_slatebuildgroup_slatebuildgroupplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='crash_outcomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='penalty_outcomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='sr_outcomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
    ]
