# Generated by Django 2.2 on 2022-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0056_auto_20220304_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='gto',
            field=models.FloatField(default=0.0),
        ),
    ]
