# Generated by Django 2.2 on 2022-03-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0058_buildplayerprojection_gto'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplayerprojection',
            name='op',
            field=models.FloatField(default=0.0),
        ),
    ]
