# Generated by Django 2.2 on 2022-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0059_buildplayerprojection_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuild',
            name='max_entrants',
            field=models.PositiveIntegerField(default=50000, verbose_name='max_entrants'),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='duplicated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='ownership_projection',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=10),
        ),
    ]
