# Generated by Django 2.2 on 2022-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0060_auto_20220309_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='duplicate_threshold',
            field=models.FloatField(default=5),
        ),
    ]
