# Generated by Django 2.2 on 2022-03-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nascar', '0061_slatebuildconfig_duplicate_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuild',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nascar.SlateBuildConfig', verbose_name='Config'),
        ),
    ]
