# Generated by Django 2.2 on 2022-03-29 13:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0062_auto_20220329_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSimLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('median', models.FloatField(db_index=True, default=0.0)),
                ('s75', models.FloatField(db_index=True, default=0.0)),
                ('s90', models.FloatField(db_index=True, default=0.0)),
                ('count', models.IntegerField(db_index=True, default=1)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsim_ineup_as_player_1', to='nascar.RaceSimDriver')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsim_ineup_as_player_2', to='nascar.RaceSimDriver')),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsim_ineup_as_player_3', to='nascar.RaceSimDriver')),
                ('player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsim_ineup_as_player_4', to='nascar.RaceSimDriver')),
                ('player_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsim_ineup_as_player_5', to='nascar.RaceSimDriver')),
                ('player_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lsim_ineup_as_player_6', to='nascar.RaceSimDriver')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineups', to='nascar.RaceSim')),
            ],
            options={
                'verbose_name': 'Optimal Lineup',
                'verbose_name_plural': 'Optimal Lineups',
                'ordering': ['-count'],
            },
        ),
    ]
