# Generated by Django 2.2 on 2022-03-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0065_auto_20220329_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesimlineup',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineup_as_player_1', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineup_as_player_2', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='player_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineup_as_player_3', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='player_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineup_as_player_4', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='player_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineup_as_player_5', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='racesimlineup',
            name='player_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_lineup_as_player_6', to='nascar.RaceSimDriver'),
        ),
    ]
