# Generated by Django 2.2 on 2022-03-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0066_auto_20220329_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='dk_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='fd_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
