# Generated by Django 2.2 on 2022-03-30 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0069_remove_racesimdriver_strategy_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimlineup',
            name='sim_score_ranks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
