# Generated by Django 2.2 on 2022-03-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0070_racesimlineup_sim_score_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimlineup',
            name='rank_median',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='racesimlineup',
            name='rank_s75',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='racesimlineup',
            name='rank_s90',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
