# Generated by Django 2.2 on 2022-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0072_auto_20220331_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesim',
            name='dk_contest_entries',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='racesim',
            name='fd_contest_entries',
            field=models.IntegerField(default=5000),
        ),
    ]
