# Generated by Django 2.2 on 2022-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0073_auto_20220331_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesimdriver',
            name='optimal_lineups_per_iteration',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='run_with_gto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='racesimdriver',
            name='run_with_lineup_rankings',
            field=models.BooleanField(default=False),
        ),
    ]
