# Generated by Django 2.2 on 2022-03-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0074_auto_20220331_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesimdriver',
            name='optimal_lineups_per_iteration',
        ),
        migrations.RemoveField(
            model_name='racesimdriver',
            name='run_with_gto',
        ),
        migrations.RemoveField(
            model_name='racesimdriver',
            name='run_with_lineup_rankings',
        ),
        migrations.AddField(
            model_name='racesim',
            name='optimal_lineups_per_iteration',
            field=models.IntegerField(default=3, verbose_name='num_lineups'),
        ),
        migrations.AddField(
            model_name='racesim',
            name='run_with_gto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='racesim',
            name='run_with_lineup_rankings',
            field=models.BooleanField(default=False),
        ),
    ]
