# Generated by Django 2.2 on 2022-03-31 16:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0075_auto_20220331_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildlineup',
            name='rank_median',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='rank_s75',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='rank_s90',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='sim_score_ranks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
