# Generated by Django 2.2 on 2022-04-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0077_auto_20220401_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesimdriver',
            name='mech_rate',
        ),
        migrations.AlterField(
            model_name='slatebuildconfig',
            name='clean_by_field',
            field=models.CharField(choices=[('projected_score', 'Projected Score'), ('projected_rank', 'Projected Rank')], default='s90', max_length=25),
        ),
    ]
