# Generated by Django 2.2 on 2022-05-05 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0079_contest_contestentry_contestprize'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentry',
            name='sim_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
