# Generated by Django 2.2 on 2022-05-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0081_contest_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='prizes_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/prizes'),
        ),
    ]
