# Generated by Django 2.2 on 2022-05-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0082_contest_prizes_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestentry',
            options={'verbose_name_plural': 'Contest Entries'},
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_1', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_2', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='player_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_3', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='player_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_4', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='player_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_5', to='nascar.RaceSimDriver'),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='player_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_6', to='nascar.RaceSimDriver'),
        ),
    ]
