# Generated by Django 2.2 on 2022-05-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0083_auto_20220506_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestBacktest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude_entries_by', models.CharField(blank=True, max_length=100, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='nascar.Contest')),
            ],
        ),
    ]
