# Generated by Django 2.2 on 2022-05-13 15:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0084_contestbacktest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestBacktestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amounts_won', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_outcomes', to='nascar.ContestBacktest')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_outcomes', to='nascar.ContestEntry')),
            ],
        ),
    ]
