# Generated by Django 2.2 on 2022-05-13 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0085_contestbacktestentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestbacktestentry',
            name='amounts_won',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
