# Generated by Django 2.2 on 2022-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0086_auto_20220513_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestbacktestentry',
            name='roi',
            field=models.FloatField(default=0.0),
        ),
    ]
