# Generated by Django 2.2 on 2022-05-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0087_contestbacktestentry_roi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestBacktestEntryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(default=1)),
                ('amount_won', models.FloatField()),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_iteration_outcomes', to='nascar.ContestBacktest')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_iteration_outcomes', to='nascar.ContestEntry')),
            ],
        ),
    ]
