# Generated by Django 2.2 on 2022-05-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0088_contestbacktestentryresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestbacktestentryresult',
            name='amount_won',
        ),
        migrations.AddField(
            model_name='contestbacktestentryresult',
            name='prize',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contestbacktestentryresult',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contestbacktestentryresult',
            name='rank_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contestbacktestentryresult',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
