# Generated by Django 2.2 on 2022-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0090_auto_20220525_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesim',
            name='for_backtest',
            field=models.BooleanField(default=False),
        ),
    ]
