# Generated by Django 2.2 on 2022-06-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0091_racesim_for_backtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestBacktestEntryResult',
        ),
    ]
