# Generated by Django 2.2 on 2022-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0093_racesimdriver_osr_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuild',
            name='field_lineups_fl',
            field=models.FileField(blank=True, null=True, upload_to='uploads/field_lineups'),
        ),
        migrations.AddField(
            model_name='slatebuild',
            name='field_lineups_rg',
            field=models.FileField(blank=True, null=True, upload_to='uploads/field_lineups'),
        ),
    ]
