# Generated by Django 2.2 on 2022-07-15 16:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0094_auto_20220715_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateBuildFieldLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('sim_score_ranks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('ownership_projection', models.DecimalField(decimal_places=9, default=0.0, max_digits=10)),
                ('duplicated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('roi', models.FloatField(db_index=True, default=0.0)),
                ('median', models.FloatField(db_index=True, default=0.0)),
                ('s75', models.FloatField(db_index=True, default=0.0)),
                ('s90', models.FloatField(db_index=True, default=0.0)),
                ('rank_median', models.FloatField(db_index=True, default=0.0)),
                ('rank_s75', models.FloatField(db_index=True, default=0.0)),
                ('rank_s90', models.FloatField(db_index=True, default=0.0)),
                ('sort_proj', models.FloatField(db_index=True, default=0.0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineups', to='nascar.SlateBuild', verbose_name='Build')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_1', to='nascar.BuildPlayerProjection')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_2', to='nascar.BuildPlayerProjection')),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_3', to='nascar.BuildPlayerProjection')),
                ('player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_4', to='nascar.BuildPlayerProjection')),
                ('player_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_5', to='nascar.BuildPlayerProjection')),
                ('player_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_6', to='nascar.BuildPlayerProjection')),
            ],
            options={
                'verbose_name': 'Field Lineup',
                'verbose_name_plural': 'Field Lineups',
                'ordering': ['-sort_proj'],
            },
        ),
    ]
