# Generated by Django 2.2 on 2022-07-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0095_slatebuildfieldlineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='nascar.SlatePlayer')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='nascar.SlatePlayer')),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='nascar.SlatePlayer')),
                ('player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p4', to='nascar.SlatePlayer')),
                ('player_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p5', to='nascar.SlatePlayer')),
                ('player_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p6', to='nascar.SlatePlayer')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_lineups', to='nascar.Slate')),
            ],
            options={
                'verbose_name': 'Slate Lineup',
                'verbose_name_plural': 'Slate Lineups',
                'ordering': ['-total_salary'],
            },
        ),
    ]
