# Generated by Django 2.2 on 2022-07-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0096_slatelineup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slateplayer',
            name='id',
        ),
        migrations.AlterField(
            model_name='slateplayer',
            name='slate_player_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
