# Generated by Django 2.2 on 2022-07-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0097_auto_20220718_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slatelineup',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='slatelineup',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='slatelineup',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='slatelineup',
            name='player_4',
        ),
        migrations.RemoveField(
            model_name='slatelineup',
            name='player_5',
        ),
        migrations.RemoveField(
            model_name='slatelineup',
            name='player_6',
        ),
        migrations.RemoveField(
            model_name='slatelineup',
            name='slate',
        ),
    ]
