# Generated by Django 2.2 on 2022-07-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0099_auto_20220718_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuild',
            name='build_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('se', 'Hi-Stakes SE'), ('mme', 'MME')], default='cash', max_length=10),
        ),
    ]
