# Generated by Django 2.2 on 2022-07-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0100_slatebuild_build_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slatebuild',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='slate',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='user',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='build',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_4',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_5',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_6',
        ),
        migrations.RemoveField(
            model_name='slatebuildgroup',
            name='build',
        ),
        migrations.RemoveField(
            model_name='slatebuildgroupplayer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='slatebuildgroupplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='build',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_4',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_5',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_6',
        ),
        migrations.DeleteModel(
            name='BuildPlayerProjection',
        ),
        migrations.DeleteModel(
            name='SlateBuild',
        ),
        migrations.DeleteModel(
            name='SlateBuildFieldLineup',
        ),
        migrations.DeleteModel(
            name='SlateBuildGroup',
        ),
        migrations.DeleteModel(
            name='SlateBuildGroupPlayer',
        ),
        migrations.DeleteModel(
            name='SlateBuildLineup',
        ),
    ]
