# Generated by Django 2.2 on 2022-07-19 13:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nascar', '0101_auto_20220719_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPlayerProjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_position', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('projection', models.FloatField(db_index=True, default=0.0, verbose_name='Proj')),
                ('ceiling', models.FloatField(db_index=True, default=0.0, verbose_name='Ceil')),
                ('s75', models.FloatField(db_index=True, default=0.0, verbose_name='s75')),
                ('in_play', models.BooleanField(default=True)),
                ('op', models.FloatField(default=0.0)),
                ('gto', models.FloatField(default=0.0)),
                ('min_exposure', models.FloatField(default=0.0, verbose_name='min')),
                ('max_exposure', models.FloatField(default=1.0, verbose_name='max')),
            ],
            options={
                'verbose_name': 'Player Projection',
                'verbose_name_plural': 'Player Projections',
                'ordering': ['-slate_player__salary'],
            },
        ),
        migrations.CreateModel(
            name='SlateBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_type', models.CharField(choices=[('cash', 'Cash'), ('se', 'Hi-Stakes SE'), ('mme', 'MME')], default='cash', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('used_in_contests', models.BooleanField(default=False, verbose_name='Used')),
                ('total_lineups', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('max_entrants', models.PositiveIntegerField(default=50000, verbose_name='max_entrants')),
                ('field_lineups_fl', models.FileField(blank=True, null=True, upload_to='uploads/field_lineups')),
                ('field_lineups_rg', models.FileField(blank=True, null=True, upload_to='uploads/field_lineups')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nascar.SlateBuildConfig', verbose_name='Config')),
                ('sim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nascar.RaceSim')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='nascar.Slate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slate Build',
                'verbose_name_plural': 'Slate Builds',
            },
        ),
        migrations.CreateModel(
            name='SlateBuildGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_from_group', models.PositiveIntegerField(default=1)),
                ('min_from_group', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='nascar.SlateBuild')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='SlateBuildLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('sim_score_ranks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('ownership_projection', models.DecimalField(decimal_places=9, default=0.0, max_digits=10)),
                ('duplicated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('roi', models.FloatField(db_index=True, default=0.0)),
                ('median', models.FloatField(db_index=True, default=0.0)),
                ('s75', models.FloatField(db_index=True, default=0.0)),
                ('s90', models.FloatField(db_index=True, default=0.0)),
                ('rank_median', models.FloatField(db_index=True, default=0.0)),
                ('rank_s75', models.FloatField(db_index=True, default=0.0)),
                ('rank_s90', models.FloatField(db_index=True, default=0.0)),
                ('sort_proj', models.FloatField(db_index=True, default=0.0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='nascar.SlateBuild', verbose_name='Build')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_1', to='nascar.BuildPlayerProjection')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_2', to='nascar.BuildPlayerProjection')),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_3', to='nascar.BuildPlayerProjection')),
                ('player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_4', to='nascar.BuildPlayerProjection')),
                ('player_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_5', to='nascar.BuildPlayerProjection')),
                ('player_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_6', to='nascar.BuildPlayerProjection')),
            ],
            options={
                'verbose_name': 'Lineup',
                'verbose_name_plural': 'Lineups',
                'ordering': ['-sort_proj'],
            },
        ),
        migrations.CreateModel(
            name='SlateBuildGroupPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='nascar.SlateBuildGroup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='nascar.BuildPlayerProjection')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='SlateBuildFieldLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('sim_score_ranks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('ownership_projection', models.DecimalField(decimal_places=9, default=0.0, max_digits=10)),
                ('duplicated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('roi', models.FloatField(db_index=True, default=0.0)),
                ('median', models.FloatField(db_index=True, default=0.0)),
                ('s75', models.FloatField(db_index=True, default=0.0)),
                ('s90', models.FloatField(db_index=True, default=0.0)),
                ('rank_median', models.FloatField(db_index=True, default=0.0)),
                ('rank_s75', models.FloatField(db_index=True, default=0.0)),
                ('rank_s90', models.FloatField(db_index=True, default=0.0)),
                ('sort_proj', models.FloatField(db_index=True, default=0.0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineups', to='nascar.SlateBuild', verbose_name='Build')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_1', to='nascar.BuildPlayerProjection')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_2', to='nascar.BuildPlayerProjection')),
                ('player_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_3', to='nascar.BuildPlayerProjection')),
                ('player_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_4', to='nascar.BuildPlayerProjection')),
                ('player_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_5', to='nascar.BuildPlayerProjection')),
                ('player_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_lineup_as_player_6', to='nascar.BuildPlayerProjection')),
            ],
            options={
                'verbose_name': 'Field Lineup',
                'verbose_name_plural': 'Field Lineups',
                'ordering': ['-sort_proj'],
            },
        ),
        migrations.AddField(
            model_name='buildplayerprojection',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='nascar.SlateBuild', verbose_name='Build'),
        ),
        migrations.AddField(
            model_name='buildplayerprojection',
            name='slate_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='nascar.SlatePlayer'),
        ),
    ]
