# Generated by Django 2.2 on 2022-07-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0102_auto_20220719_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slatebuildfieldlineup',
            options={'ordering': ['-median'], 'verbose_name': 'Field Lineup', 'verbose_name_plural': 'Field Lineups'},
        ),
        migrations.AlterModelOptions(
            name='slatebuildlineup',
            options={'ordering': ['-median'], 'verbose_name': 'Lineup', 'verbose_name_plural': 'Lineups'},
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='duplicated',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='ownership_projection',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='rank_median',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='rank_s75',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='rank_s90',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='roi',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='sim_score_ranks',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='sort_proj',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='duplicated',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='ownership_projection',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_4',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_5',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='player_6',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='rank_median',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='rank_s75',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='rank_s90',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='roi',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='sim_score_ranks',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='sort_proj',
        ),
        migrations.RemoveField(
            model_name='slatebuildlineup',
            name='total_salary',
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='slate_lineup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='nascar.SlateLineup', verbose_name='Lineup'),
            preserve_default=False,
        ),
    ]
