# Generated by Django 2.2 on 2022-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0104_auto_20220721_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayer',
            name='csv_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
