# Generated by Django 2.2 on 2022-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0105_slateplayer_csv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildfieldlineup',
            name='opponent_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='build_type',
            field=models.CharField(choices=[('h2h', 'Head-to-Head'), ('cash', '50/50s'), ('se', 'Hi-Stakes SE'), ('mme', 'MME')], default='cash', max_length=10),
        ),
    ]
