# Generated by Django 2.2 on 2022-07-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0106_auto_20220725_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slatebuild',
            old_name='field_lineups_fl',
            new_name='field_lineup_upload',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='field_lineups_rg',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='max_entrants',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='total_lineups',
        ),
        migrations.RemoveField(
            model_name='slatebuild',
            name='used_in_contests',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_4',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_5',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='player_6',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='sim_scores',
        ),
        migrations.RemoveField(
            model_name='slatebuildfieldlineup',
            name='total_salary',
        ),
        migrations.AddField(
            model_name='slatebuildfieldlineup',
            name='slate_lineup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nascar.SlateLineup', verbose_name='Lineup'),
        ),
    ]
