# Generated by Django 2.2 on 2022-07-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nascar', '0107_auto_20220725_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildfieldlineup',
            name='slate_lineup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_lineups', to='nascar.SlateLineup', verbose_name='Lineup'),
        ),
    ]
