# Generated by Django 2.2 on 2022-06-21 13:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('entries_file', models.FileField(blank=True, null=True, upload_to='uploads/entries')),
                ('prizes_file', models.FileField(blank=True, null=True, upload_to='uploads/prizes')),
                ('sim_file', models.FileField(blank=True, null=True, upload_to='uploads/sims')),
                ('num_iterations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContestBacktest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='backtesting.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='ContestEntryPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='ContestPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rank', models.IntegerField(default=1)),
                ('max_rank', models.IntegerField(default=1)),
                ('prize', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='backtesting.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=50)),
                ('entry_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lineup_str', models.TextField(blank=True, null=True)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='backtesting.Contest')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_1', to='backtesting.ContestEntryPlayer')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_2', to='backtesting.ContestEntryPlayer')),
                ('player_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_3', to='backtesting.ContestEntryPlayer')),
                ('player_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_4', to='backtesting.ContestEntryPlayer')),
                ('player_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_5', to='backtesting.ContestEntryPlayer')),
                ('player_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_entry_as_player_6', to='backtesting.ContestEntryPlayer')),
            ],
            options={
                'verbose_name_plural': 'Contest Entries',
            },
        ),
        migrations.CreateModel(
            name='ContestBacktestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_won', models.FloatField(default=0.0)),
                ('roi', models.FloatField(default=0.0)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_outcomes', to='backtesting.ContestBacktest')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_outcomes', to='backtesting.ContestEntry')),
            ],
        ),
    ]
