# Generated by Django 2.2 on 2022-06-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentryplayer',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='backtesting.Contest'),
            preserve_default=False,
        ),
    ]
