# Generated by Django 2.2 on 2021-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Backtest',
                'verbose_name_plural': 'Backtests',
                'ordering': ('-created',),
            },
        ),
    ]
