# Generated by Django 2.2 on 2021-06-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0002_backtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestSlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slates', to='nfl.Backtest')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='nfl.Slate')),
            ],
            options={
                'verbose_name': 'Slate',
                'verbose_name_plural': 'Slates',
                'ordering': ('-slate__week__year', '-slate__week__num'),
            },
        ),
    ]
