# Generated by Django 2.2 on 2021-06-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0003_backtestslate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slatebuild',
            name='tag',
        ),
        migrations.AddField(
            model_name='slatebuild',
            name='backtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfl.BacktestSlate'),
        ),
        migrations.DeleteModel(
            name='Tagulous_SlateBuild_tag',
        ),
    ]
