# Generated by Django 2.2 on 2021-06-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0004_auto_20210610_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel'), ('yahoo', 'Yahoo')], default='fanduel', max_length=50),
        ),
    ]
