# Generated by Django 2.2 on 2021-06-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0005_backtest_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='lineup_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfl.SlateBuildConfig'),
        ),
    ]
