# Generated by Django 2.2 on 2021-06-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0006_backtest_lineup_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProjectionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('maps_to', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Selection Criteria Field',
                'verbose_name_plural': 'Selection Criteria Fields',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerThresholdCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('eq', '=='), ('gt', '>'), ('lt', '<'), ('gte', '>='), ('lte', '<='), ('ne', '!=')], default='eq', max_length=3)),
                ('value', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('projection_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.PlayerProjectionField')),
            ],
        ),
    ]
