# Generated by Django 2.2 on 2021-06-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0007_playerprojectionfield_playerthresholdcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionThresholdCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_pos', models.CharField(max_length=5)),
                ('operator', models.CharField(choices=[('eq', '=='), ('gt', '>'), ('lt', '<'), ('gte', '>='), ('lte', '<='), ('ne', '!=')], default='eq', max_length=3)),
                ('value', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('projection_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.PlayerProjectionField')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerThresholdCondition',
        ),
    ]
