# Generated by Django 2.2 on 2021-06-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0011_groupcreationrule_lineupconstructionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateBuildGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_from_group', models.PositiveIntegerField(default=1)),
                ('min_from_group', models.PositiveIntegerField(default=0)),
                ('total_exposure', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('active', models.BooleanField(default=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='nfl.SlateBuild')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AlterField(
            model_name='groupcreationrule',
            name='construction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_rules', to='nfl.LineupConstructionRule'),
        ),
        migrations.CreateModel(
            name='SlateBuildGroupPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='nfl.SlateBuildGroup')),
                ('slate_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='nfl.SlatePlayer')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
