# Generated by Django 2.2 on 2021-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0012_auto_20210611_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PositionThreshold',
        ),
    ]
