# Generated by Django 2.2 on 2021-06-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0013_delete_positionthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='in_play_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='nfl.PlayerSelectionCriteria'),
        ),
        migrations.AddField(
            model_name='backtest',
            name='lineup_construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='nfl.LineupConstructionRule'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='lineup_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='nfl.SlateBuildConfig'),
        ),
    ]
