# Generated by Django 2.2 on 2021-06-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0014_auto_20210615_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerselectioncriteria',
            name='dst_threshold',
            field=models.TextField(blank=True, help_text='Forumla for picking dsts in play', null=True),
        ),
        migrations.AlterField(
            model_name='playerselectioncriteria',
            name='rb_threshold',
            field=models.TextField(blank=True, help_text='Forumla for picking rbs in play', null=True),
        ),
        migrations.AlterField(
            model_name='playerselectioncriteria',
            name='te_threshold',
            field=models.TextField(blank=True, help_text='Forumla for picking tes in play', null=True),
        ),
        migrations.AlterField(
            model_name='playerselectioncriteria',
            name='wr_threshold',
            field=models.TextField(blank=True, help_text='Forumla for picking wrs in play', null=True),
        ),
    ]
