# Generated by Django 2.2 on 2021-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0017_slatebuildstack_contains_top_pc'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackConstructionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel'), ('yahoo', 'Yahoo')], default='fanduel', max_length=50)),
                ('lock_top_pc', models.BooleanField(default=False)),
                ('top_pc_margin', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Stack Construction Rule',
                'verbose_name_plural': 'Stack Construction Rules',
                'ordering': ['name'],
            },
        ),
    ]
