# Generated by Django 2.2 on 2021-06-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0019_backtest_stack_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPlayerProjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Proj')),
                ('adjusted_opportunity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='AO')),
                ('rb_group_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rb_group', models.PositiveIntegerField(blank=True, null=True)),
                ('balanced_projection', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('team_total', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='tt')),
                ('game_total', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='gt')),
                ('spread', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('in_play', models.BooleanField(default=True)),
                ('stack_only', models.BooleanField(default=False, help_text='Player is only in pool when stacked with QB or opposing QB', verbose_name='SO')),
                ('qb_stack_only', models.BooleanField(default=False, help_text='Generate QB stacks with this player', verbose_name='SwQB')),
                ('opp_qb_stack_only', models.BooleanField(default=False, help_text='Generate Opp QB stacks with this player', verbose_name='SwOQB')),
                ('at_most_one_in_stack', models.BooleanField(default=False, help_text='Generate stacks with only 1 of players with this designation', verbose_name='AM1')),
                ('at_least_one_in_lineup', models.BooleanField(default=False, help_text='At least one player with this designation should appear in every lineup', verbose_name='AL1')),
                ('at_least_two_in_lineup', models.BooleanField(default=False, help_text='At least two players with this designation should appear in every lineup', verbose_name='AL2')),
                ('locked', models.BooleanField(default=False)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='nfl.SlateBuild', verbose_name='Build')),
                ('slate_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='build_projection', to='nfl.SlatePlayer')),
            ],
            options={
                'verbose_name': 'Player Projection',
                'verbose_name_plural': 'Player Projections',
                'ordering': ['-projection'],
            },
        ),
    ]
