# Generated by Django 2.2 on 2021-06-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0020_buildplayerprojection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuild',
            name='backtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nfl.BacktestSlate'),
        ),
    ]
