# Generated by Django 2.2 on 2021-06-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0022_auto_20210615_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slatebuild',
            name='balance_rbs',
        ),
        migrations.AddField(
            model_name='backtest',
            name='lineups_per_slate',
            field=models.PositiveSmallIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='slate_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_projections', to='nfl.SlatePlayer'),
        ),
    ]
