# Generated by Django 2.2 on 2021-06-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0023_auto_20210615_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slatebuildgroup',
            name='total_exposure',
        ),
    ]
