# Generated by Django 2.2 on 2021-06-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0024_remove_slatebuildgroup_total_exposure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildstack',
            name='opp_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opp_stacks', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildstack',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_stacks', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildstack',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2_stacks', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildstack',
            name='qb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb_stacks', to='nfl.BuildPlayerProjection'),
        ),
    ]
