# Generated by Django 2.2 on 2021-06-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0026_slatebuild_stack_cutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='stack_cutoff',
            field=models.SmallIntegerField(default=0, help_text='# of allowe stacks (ex. 80 for FD, and 90 for DK)'),
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='stack_cutoff',
            field=models.SmallIntegerField(default=0, help_text='# of allowe stacks (ex. 80 for FD, and 90 for DK)'),
        ),
    ]
