# Generated by Django 2.2 on 2021-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0027_auto_20210621_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuild',
            name='pct_complete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='slatebuild',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('complete', 'Complete'), ('error', 'Error')], default='not_started', max_length=25),
        ),
    ]
