# Generated by Django 2.2 on 2021-06-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0028_auto_20210621_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals_dst', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='flex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals_flex', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='qb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals_qb', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='rb1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals_rb1', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='rb2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals_rb2', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='te',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals_te', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='wr1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals_wr1', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='wr2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals_wr2', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='wr3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuals_wr3', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='flex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='qb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='rb1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb1', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='rb2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb2', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='te',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='te', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='wr1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr1', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='wr2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr2', to='nfl.BuildPlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='wr3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr3', to='nfl.BuildPlayerProjection'),
        ),
    ]
