# Generated by Django 2.2 on 2021-06-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0029_auto_20210622_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='completed_lineups',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backtest',
            name='total_lineups',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
