# Generated by Django 2.2 on 2021-06-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0030_auto_20210622_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slatebuild',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
