# Generated by Django 2.2 on 2021-06-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0032_auto_20210630_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='optimals_pct_complete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='backtest',
            name='total_optimals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
