# Generated by Django 2.2 on 2021-07-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0033_auto_20210630_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backtest',
            options={'ordering': ('-created',), 'verbose_name': 'Backtest', 'verbose_name_plural': 'Backtesting Center'},
        ),
        migrations.AlterField(
            model_name='backtest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Backtest'),
        ),
    ]
