# Generated by Django 2.2 on 2021-07-21 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0036_auto_20210719_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuild',
            name='elapsed_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
