# Generated by Django 2.2 on 2021-07-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0039_auto_20210722_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildstack',
            name='lineups_created',
            field=models.BooleanField(default=False),
        ),
    ]
