# Generated by Django 2.2 on 2021-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0041_slatebuildstack_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='great_build_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='backtest',
            name='median_cash_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='backtest',
            name='median_great_build_diff',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='backtest',
            name='median_half_pct_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='backtest',
            name='median_one_pct_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='backtest',
            name='optimal_build_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
