# Generated by Django 2.2 on 2021-07-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0042_auto_20210728_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuild',
            name='construction_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slatebuild',
            name='projections_ready',
            field=models.BooleanField(default=False),
        ),
    ]
