# Generated by Django 2.2 on 2021-08-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0043_auto_20210728_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildstack',
            name='optimals_created',
            field=models.BooleanField(default=False),
        ),
    ]
