# Generated by Django 2.2 on 2021-08-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0045_slateplayerprojection_ownership_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlatePlayerOwnershipProjectionSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.FileField(upload_to='uploads/ownership_projections')),
                ('slate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_projections_sheets', to='nfl.Slate')),
            ],
        ),
    ]
