# Generated by Django 2.2 on 2021-08-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0046_slateplayerownershipprojectionsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplayerprojection',
            name='ownership_projection',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Own'),
        ),
    ]
