# Generated by Django 2.2 on 2021-08-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0047_buildplayerprojection_ownership_projection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slateplayerprojection',
            options={'ordering': ['-projection'], 'verbose_name': 'Base Player Projection', 'verbose_name_plural': 'Base Player Projections'},
        ),
        migrations.AlterField(
            model_name='slateplayerprojection',
            name='ownership_projection',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Own'),
        ),
    ]
