# Generated by Django 2.2 on 2021-08-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0049_auto_20210813_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='target_score_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
