# Generated by Django 2.2 on 2021-08-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0050_slatebuildconfig_target_score_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slatebuildconfig',
            name='target_score_threshold',
        ),
        migrations.AddField(
            model_name='slatebuildconfig',
            name='lineup_removal_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
