# Generated by Django 2.2 on 2021-08-27 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0051_auto_20210817_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='ceiling',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ceil'),
        ),
        migrations.AddField(
            model_name='slateplayerprojection',
            name='floor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Flr'),
        ),
        migrations.AddField(
            model_name='slateplayerprojection',
            name='stdev',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Stdev'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='elapsed_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='in_play_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='nfl.PlayerSelectionCriteria', verbose_name='IPC'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='lineup_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='nfl.SlateBuildConfig', verbose_name='CFG'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='lineup_construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='nfl.LineupConstructionRule', verbose_name='LC'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='stack_construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='nfl.StackConstructionRule', verbose_name='SC'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='total_lineups',
            field=models.PositiveIntegerField(default=0, verbose_name='TL'),
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nfl.SlateBuildConfig', verbose_name='CFG'),
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='in_play_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nfl.PlayerSelectionCriteria', verbose_name='IPC'),
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='lineup_construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nfl.LineupConstructionRule', verbose_name='LC'),
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='stack_construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='nfl.StackConstructionRule', verbose_name='SC'),
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='stack_cutoff',
            field=models.SmallIntegerField(default=0, help_text='# of allowe stacks (ex. 80 for FD, and 90 for DK)', verbose_name='SO'),
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='target_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='TRGT'),
        ),
    ]
