# Generated by Django 2.2 on 2021-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0054_contest_play_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='allow_qb_dst_from_same_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='balanced_projection',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='BP'),
        ),
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='rb_group',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RBG'),
        ),
        migrations.AlterField(
            model_name='slateplayerprojection',
            name='balanced_projection',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='BP'),
        ),
        migrations.AlterField(
            model_name='slateplayerprojection',
            name='rb_group',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RBG'),
        ),
    ]
