# Generated by Django 2.2 on 2021-09-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0056_auto_20210901_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildlineup',
            name='ownership_projection',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='ownership_projection_percentile',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='projection_percentile',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
