# Generated by Django 2.2 on 2021-09-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0060_auto_20210902_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlatePlayerImportSheet',
        ),
    ]
