# Generated by Django 2.2 on 2021-09-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0061_delete_slateplayerimportsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='salaries',
            field=models.FileField(blank=True, null=True, upload_to='uploads/salaries'),
        ),
        migrations.AddField(
            model_name='slate',
            name='salaries_sheet_type',
            field=models.CharField(choices=[('site', 'Salary File'), ('fantasycruncher', 'FantasyCruncher Export')], default='site', max_length=255),
        ),
        migrations.AddField(
            model_name='slateprojectionsheet',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders')], default='4for4', max_length=255),
        ),
    ]
