# Generated by Django 2.2 on 2021-09-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0062_auto_20210905_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='fdraft_name',
            new_name='etr_name',
        ),
        migrations.RenameField(
            model_name='alias',
            old_name='ss_name',
            new_name='rg_name',
        ),
        migrations.RemoveField(
            model_name='alias',
            name='yahoo_name',
        ),
        migrations.CreateModel(
            name='MissingAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_1', to='nfl.Alias')),
                ('alias_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_2', to='nfl.Alias')),
                ('alias_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_3', to='nfl.Alias')),
            ],
            options={
                'verbose_name': 'Missing Alias',
                'verbose_name_plural': 'Missing Aliases',
            },
        ),
    ]
