# Generated by Django 2.2 on 2021-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0063_auto_20210907_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingalias',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel'), ('yahoo', 'Yahoo'), ('4for4', '4For4'), ('awesemo', 'Awesemo'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders')], default='fanduel', max_length=50),
        ),
    ]
