# Generated by Django 2.2 on 2021-09-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0064_missingalias_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetColumnHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_site', models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher')], default='4for4', max_length=255)),
                ('site', models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel'), ('yahoo', 'Yahoo')], default='fanduel', max_length=50)),
                ('column_player_name', models.CharField(max_length=50)),
                ('column_median_projection', models.CharField(max_length=50)),
                ('column_floor_projection', models.CharField(blank=True, max_length=50, null=True)),
                ('column_ceiling_projection', models.CharField(blank=True, max_length=50, null=True)),
                ('column_rush_att_projection', models.CharField(blank=True, max_length=50, null=True)),
                ('column_rec_projection', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Column Headers',
                'verbose_name_plural': 'Column Headers',
            },
        ),
        migrations.AlterField(
            model_name='missingalias',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel'), ('yahoo', 'Yahoo'), ('4for4', '4For4'), ('awesemo', 'Awesemo'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='slateprojectionsheet',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher')], default='4for4', max_length=255),
        ),
    ]
