# Generated by Django 2.2 on 2021-09-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0066_auto_20210907_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetcolumnheaders',
            name='column_team',
            field=models.CharField(default='Team', max_length=50),
            preserve_default=False,
        ),
    ]
