# Generated by Django 2.2 on 2021-09-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0068_slateprojectionsheet_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlatePlayerRawProjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_site', models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims')], default='4for4', max_length=255)),
                ('projection', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Proj')),
                ('floor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Flr')),
                ('ceiling', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ceil')),
                ('stdev', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Stdev')),
                ('ownership_projection', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Own')),
                ('adjusted_opportunity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='AO')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('projection_percentile', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('ownership_projection_percentile', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('value_projection_percentile', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('adjusted_opportunity_percentile', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('slate_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_projections', to='nfl.SlatePlayer')),
            ],
            options={
                'verbose_name': 'Raw Player Projection',
                'verbose_name_plural': 'Raw Player Projections',
                'ordering': ['-projection'],
            },
        ),
    ]
