# Generated by Django 2.2 on 2021-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0069_slateplayerrawprojection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetcolumnheaders',
            name='column_own_projection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
