# Generated by Django 2.2 on 2021-09-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0070_sheetcolumnheaders_column_own_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateprojectionsheet',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
