# Generated by Django 2.2 on 2021-09-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0071_auto_20210907_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateprojectionsheet',
            name='slate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='nfl.Slate'),
        ),
    ]
