# Generated by Django 2.2 on 2021-09-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0074_auto_20210908_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcreationrule',
            name='at_most',
            field=models.PositiveSmallIntegerField(default=0, help_text='At most X players meeting threshold, where X is the number you input'),
        ),
        migrations.AddField(
            model_name='groupcreationrule',
            name='at_most_threshold',
            field=models.TextField(blank=True, help_text='Forumla for limit threshold', null=True),
        ),
    ]
