# Generated by Django 2.2 on 2021-09-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0076_auto_20210908_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='rb_group_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
