# Generated by Django 2.2 on 2021-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0077_auto_20210909_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='rb_group',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='RBG'),
        ),
    ]
