# Generated by Django 2.2 on 2021-09-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0078_auto_20210909_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slateplayerprojection',
            name='game_total',
        ),
        migrations.RemoveField(
            model_name='slateplayerprojection',
            name='spread',
        ),
        migrations.RemoveField(
            model_name='slateplayerprojection',
            name='team_total',
        ),
    ]
