# Generated by Django 2.2 on 2021-09-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0079_auto_20210910_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildplayerprojection',
            name='game_total',
        ),
        migrations.RemoveField(
            model_name='buildplayerprojection',
            name='spread',
        ),
        migrations.RemoveField(
            model_name='buildplayerprojection',
            name='team_total',
        ),
    ]
