# Generated by Django 2.2 on 2021-09-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0080_auto_20210910_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayer',
            name='slate_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfl.SlateGame'),
        ),
    ]
