# Generated by Django 2.2 on 2021-09-11 21:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0082_auto_20210910_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='sim_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=4), blank=True, null=True, size=None),
        ),
    ]
