# Generated by Django 2.2 on 2021-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0087_slatebuildstack_sim_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='slategame',
            name='zscore',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Z-Score'),
        ),
    ]
