# Generated by Django 2.2 on 2021-09-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0088_slategame_zscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='slategame',
            name='ownership',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Ownership'),
        ),
        migrations.AddField(
            model_name='slategame',
            name='rating',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Rating'),
        ),
    ]
