# Generated by Django 2.2 on 2021-09-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0089_auto_20210922_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateplayer',
            name='slate_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='nfl.SlateGame'),
        ),
    ]
