# Generated by Django 2.2 on 2021-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0091_auto_20210922_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='slategame',
            name='ownership_zscore',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Own Z-Score'),
        ),
    ]
