# Generated by Django 2.2 on 2021-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0092_slategame_ownership_zscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='slategame',
            name='avg_stack_ceiling',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Avg Stack Ceiling'),
        ),
    ]
