# Generated by Django 2.2 on 2021-09-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0094_slatebuildstack_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='zscore',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Z-Score'),
        ),
    ]
