# Generated by Django 2.2 on 2021-09-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0095_slateplayerprojection_zscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='ao_zscore',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Z-Score'),
        ),
    ]
