# Generated by Django 2.2 on 2021-09-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0096_slateplayerprojection_ao_zscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildstack',
            name='opp_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_stacks', to='nfl.BuildPlayerProjection'),
        ),
    ]
