# Generated by Django 2.2 on 2021-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0097_auto_20210928_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='use_super_stacks',
            field=models.BooleanField(default=False),
        ),
    ]
