# Generated by Django 2.2 on 2021-10-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0099_auto_20210930_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildstack',
            name='mini_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_stacks', to='nfl.SlateGame'),
        ),
    ]
