# Generated by Django 2.2 on 2021-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0100_slatebuildstack_mini_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildstack',
            name='projection_zscore',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Z-Score'),
        ),
    ]
