# Generated by Django 2.2 on 2021-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0101_slatebuildstack_projection_zscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='player_contest',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sims'),
        ),
        migrations.AddField(
            model_name='slate',
            name='player_outcomes',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sims'),
        ),
    ]
