# Generated by Django 2.2 on 2021-10-01 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0103_auto_20211001_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='outcomes_sheet',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sims'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='outcomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), size=None), blank=True, null=True, size=None),
        ),
    ]
