# Generated by Django 2.2 on 2021-10-06 13:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0107_auto_20211006_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='sim_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='sim_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=None),
        ),
    ]
