# Generated by Django 2.2 on 2021-10-07 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0108_auto_20211006_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='actual',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='ev',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='expected_lineup_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='salary',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='sim_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5), blank=True, null=True, size=None),
        ),
    ]
