# Generated by Django 2.2 on 2021-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0109_auto_20211007_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='ev',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='expected_lineup_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='order_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='ownership_projection',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='projection',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='salary',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
