# Generated by Django 2.2 on 2021-10-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0111_auto_20211009_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='adjusted_opportunity',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='AO'),
        ),
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='in_play',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='ownership_projection',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Own'),
        ),
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='projection',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Proj'),
        ),
        migrations.AlterField(
            model_name='buildplayerprojection',
            name='value',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
