# Generated by Django 2.2 on 2021-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0117_auto_20211013_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildactualslineup',
            name='mean',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='mean',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
