# Generated by Django 2.2 on 2021-10-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0118_auto_20211014_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='use_simulation',
            field=models.BooleanField(default=False),
        ),
    ]
