# Generated by Django 2.2 on 2021-10-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0119_slatebuildconfig_use_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildactualslineup',
            name='sim_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='sim_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='mean',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slatebuildactualslineup',
            name='std',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='mean',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='std',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
