# Generated by Django 2.2 on 2021-10-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0120_auto_20211015_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplayerprojection',
            name='sim_projection',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Sim Proj'),
        ),
    ]
