# Generated by Django 2.2 on 2021-10-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0121_buildplayerprojection_sim_projection'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplayerprojection',
            name='gto',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='GTO'),
        ),
    ]
