# Generated by Django 2.2 on 2021-10-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0122_buildplayerprojection_gto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateBuildTopStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains_top_pc', models.BooleanField(db_index=True, default=False)),
                ('salary', models.PositiveIntegerField(db_index=True)),
                ('projection', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('times_used', models.PositiveIntegerField(db_index=True, default=0)),
                ('gto', models.DecimalField(db_index=True, decimal_places=4, max_digits=5)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_stacks', to='nfl.SlateBuild', verbose_name='Build')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_stacks', to='nfl.SlateGame')),
                ('opp_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_top_stacks', to='nfl.BuildPlayerProjection')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_top_stacks', to='nfl.BuildPlayerProjection')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2_top_stacks', to='nfl.BuildPlayerProjection')),
                ('qb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb_top_stacks', to='nfl.BuildPlayerProjection')),
            ],
            options={
                'verbose_name': 'Top Stack',
                'verbose_name_plural': 'Top Stacks',
                'ordering': ['-gto', '-projection'],
            },
        ),
    ]
