# Generated by Django 2.2 on 2021-10-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0124_auto_20211020_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='optimize_with_ceilings',
            field=models.BooleanField(default=False),
        ),
    ]
