# Generated by Django 2.2 on 2021-10-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0125_slatebuildconfig_optimize_with_ceilings'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='use_top_stacks',
            field=models.BooleanField(default=False),
        ),
    ]
