# Generated by Django 2.2 on 2021-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0126_slatebuildconfig_use_top_stacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildtopstack',
            name='projection',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='slatebuildtopstack',
            name='salary',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
