# Generated by Django 2.2 on 2021-10-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0127_auto_20211022_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeilingProjectionRangeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_projection', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_projection', models.DecimalField(decimal_places=2, max_digits=4)),
                ('value_to_assign', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
