# Generated by Django 2.2 on 2021-10-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0128_ceilingprojectionrangemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='ev_cutoff',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='slatebuildconfig',
            name='lineup_multiplier',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='slatebuildconfig',
            name='std_cutoff',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='slatebuild',
            name='total_optimals',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='#opt'),
        ),
    ]
