# Generated by Django 2.2 on 2021-10-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0129_auto_20211025_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='outcomes',
        ),
        migrations.AddField(
            model_name='contest',
            name='use_for_sims',
            field=models.BooleanField(default=False),
        ),
    ]
