# Generated by Django 2.2 on 2021-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0131_contest_use_for_actuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='ceiling_zscore',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Ceiling Z-Score'),
        ),
    ]
