# Generated by Django 2.2 on 2021-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0132_slateplayerprojection_ceiling_zscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackconstructionrule',
            name='criteria',
            field=models.TextField(blank=True, help_text='Critertia for stack inclusion', null=True),
        ),
    ]
