# Generated by Django 2.2 on 2021-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0135_auto_20211103_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slatebuildconfig',
            name='use_leverage',
        ),
        migrations.AddField(
            model_name='slatebuildconfig',
            name='qb_leverage',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
