# Generated by Django 2.2 on 2021-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0136_auto_20211103_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='stack_player_leverage',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
