# Generated by Django 2.2 on 2021-11-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0137_slatebuildconfig_stack_player_leverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slatebuildconfig',
            old_name='qb_leverage',
            new_name='player_high_owned_threshold',
        ),
        migrations.RenameField(
            model_name='slatebuildconfig',
            old_name='stack_player_leverage',
            new_name='qb_high_owned_threshold',
        ),
        migrations.AddField(
            model_name='slatebuildconfig',
            name='qb_low_owned_threshold',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
