# Generated by Django 2.2 on 2021-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0138_auto_20211104_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildlineup',
            name='s75',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='s90',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
