# Generated by Django 2.2 on 2021-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0139_auto_20211110_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildlineup',
            name='median',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
