# Generated by Django 2.2 on 2021-11-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0141_slatebuildconfig_lineup_removal_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildconfig',
            name='lineup_removal_by',
            field=models.CharField(choices=[('projection', 'Projection'), ('median', 'Median'), ('s90', 'Ceiling')], default='projection', max_length=15),
        ),
    ]
