# Generated by Django 2.2 on 2021-11-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0142_auto_20211116_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='slategame',
            name='game_sim',
            field=models.TextField(blank=True, null=True),
        ),
    ]
