# Generated by Django 2.2 on 2021-11-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanduel', '0007_contest_last_page_processed'),
        ('nfl', '0143_slategame_game_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='fanduel_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fanduel.Contest'),
        ),
    ]
