# Generated by Django 2.2 on 2021-11-24 12:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0144_contest_fanduel_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateplayerprojection',
            name='sim_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=None),
        ),
    ]
