# Generated by Django 2.2 on 2021-11-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0145_auto_20211124_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupImportSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.FileField(upload_to='uploads/groups')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.SlateBuild')),
            ],
        ),
    ]
