# Generated by Django 2.2 on 2021-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0148_auto_20211130_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplayerprojection',
            name='disallow_ministack',
            field=models.BooleanField(default=False, verbose_name='No Mini'),
        ),
        migrations.AddField(
            model_name='buildplayerprojection',
            name='use_as_antileverage',
            field=models.BooleanField(default=False, verbose_name='Anti Lev'),
        ),
    ]
