# Generated by Django 2.2 on 2021-12-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0150_alias_yahoo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slateplayerprojection',
            name='at_least_one_in_lineup',
        ),
        migrations.RemoveField(
            model_name='slateplayerprojection',
            name='at_least_two_in_lineup',
        ),
        migrations.RemoveField(
            model_name='slateplayerprojection',
            name='at_most_one_in_stack',
        ),
    ]
