# Generated by Django 2.2 on 2021-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0153_auto_20211203_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceilingprojectionrangemapping',
            name='max_projection',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ceilingprojectionrangemapping',
            name='min_projection',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ceilingprojectionrangemapping',
            name='value_to_assign',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ceilingprojectionrangemapping',
            name='yh_value_to_assign',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
