# Generated by Django 2.2 on 2021-12-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0154_auto_20211203_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateplayerownershipprojectionsheet',
            name='slate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_projections_sheets', to='nfl.Slate'),
        ),
    ]
