# Generated by Django 2.2 on 2021-12-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0157_auto_20211205_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slate',
            name='salaries_sheet_type',
            field=models.CharField(choices=[('site', 'Salary File'), ('fantasycruncher', 'FantasyCruncher Export'), ('sabersim', 'SaberSim Export')], default='site', max_length=255),
        ),
        migrations.AlterField(
            model_name='slateplayer',
            name='ownership',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
