# Generated by Django 2.2 on 2021-12-09 15:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0158_auto_20211209_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateFieldLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=None)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='nfl.SlatePlayerProjection')),
                ('flex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex', to='nfl.SlatePlayerProjection')),
                ('qb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb', to='nfl.SlatePlayerProjection')),
                ('rb1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb1', to='nfl.SlatePlayerProjection')),
                ('rb2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb2', to='nfl.SlatePlayerProjection')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineups', to='nfl.Slate', verbose_name='Slate')),
                ('te', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='te', to='nfl.SlatePlayerProjection')),
                ('wr1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr1', to='nfl.SlatePlayerProjection')),
                ('wr2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr2', to='nfl.SlatePlayerProjection')),
                ('wr3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr3', to='nfl.SlatePlayerProjection')),
            ],
        ),
    ]
