# Generated by Django 2.2 on 2021-12-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0159_slatefieldlineup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slatebuildlineup',
            old_name='ev',
            new_name='roi',
        ),
    ]
