# Generated by Django 2.2 on 2021-12-18 19:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0160_auto_20211217_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateFieldOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=None)),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_outcomes', to='nfl.Slate', verbose_name='Slate')),
            ],
        ),
    ]
