# Generated by Django 2.2 on 2021-12-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0161_slatefieldoutcome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlateFieldOutcome',
        ),
    ]
