# Generated by Django 2.2 on 2022-01-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0163_slatebuildconfig_lineup_pool_per_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildconfig',
            name='lineup_pool_per_stack',
            field=models.SmallIntegerField(default=100),
        ),
    ]
