# Generated by Django 2.2 on 2022-09-02 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0164_auto_20220105_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='nfl.SlatePlayer')),
                ('flex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex', to='nfl.SlatePlayer')),
                ('qb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb', to='nfl.SlatePlayer')),
                ('rb1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb1', to='nfl.SlatePlayer')),
                ('rb2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb2', to='nfl.SlatePlayer')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_lineups', to='nfl.Slate')),
                ('te', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='te', to='nfl.SlatePlayer')),
                ('wr1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr1', to='nfl.SlatePlayer')),
                ('wr2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr2', to='nfl.SlatePlayer')),
                ('wr3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr3', to='nfl.SlatePlayer')),
            ],
            options={
                'verbose_name': 'Slate Lineup',
                'verbose_name_plural': 'Slate Lineups',
                'ordering': ['-total_salary'],
            },
        ),
    ]
