# Generated by Django 2.2 on 2022-09-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0165_slatelineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='dst_threshold',
            field=models.TextField(blank=True, help_text='Forumla for picking dsts in play', null=True),
        ),
        migrations.AddField(
            model_name='slate',
            name='qb_threshold',
            field=models.TextField(blank=True, help_text='Forumla for picking qbs in play', null=True),
        ),
        migrations.AddField(
            model_name='slate',
            name='rb_threshold',
            field=models.TextField(blank=True, help_text='Forumla for picking rbs in play', null=True),
        ),
        migrations.AddField(
            model_name='slate',
            name='te_threshold',
            field=models.TextField(blank=True, help_text='Forumla for picking tes in play', null=True),
        ),
        migrations.AddField(
            model_name='slate',
            name='wr_threshold',
            field=models.TextField(blank=True, help_text='Forumla for picking wrs in play', null=True),
        ),
    ]
