# Generated by Django 2.2 on 2022-09-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0166_auto_20220902_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='in_play_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slates', to='nfl.PlayerSelectionCriteria', verbose_name='IPC'),
        ),
    ]
