# Generated by Django 2.2 on 2022-09-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0168_auto_20220902_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindWinnerBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_type', models.CharField(choices=[('h2h', 'Head-to-Head'), ('cash', '50/50s'), ('se', 'Hi-Stakes SE'), ('mme', 'MME')], default='h2h', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('field_lineup_upload', models.FileField(blank=True, null=True, upload_to='uploads/field_lineups')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_winner_builds', to='nfl.Slate')),
            ],
            options={
                'verbose_name': 'Find Winner Build',
                'verbose_name_plural': 'Find Winner Builds',
            },
        ),
    ]
