# Generated by Django 2.2 on 2022-09-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0170_winninglineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldLineupToBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('median', models.FloatField(db_index=True, default=0.0)),
                ('s75', models.FloatField(db_index=True, default=0.0)),
                ('s90', models.FloatField(db_index=True, default=0.0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_lineups_to_beat', to='nfl.FindWinnerBuild', verbose_name='Build')),
                ('slate_lineup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_lineups_to_beat', to='nfl.SlateLineup', verbose_name='Lineup')),
            ],
            options={
                'verbose_name': 'Field Lineup',
                'verbose_name_plural': 'Field Lineups',
                'ordering': ['-median'],
            },
        ),
        migrations.CreateModel(
            name='LineupMatchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rate', models.FloatField(db_index=True, default=0.0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='nfl.FindWinnerBuild', verbose_name='Build')),
                ('field_lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='nfl.FieldLineupToBeat')),
                ('slate_lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='nfl.SlateLineup')),
            ],
            options={
                'verbose_name': 'Lineup Matchup',
                'verbose_name_plural': 'Lineup Matchups',
                'ordering': ['-win_rate'],
            },
        ),
    ]
