# Generated by Django 2.2 on 2022-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0171_fieldlineuptobeat_lineupmatchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='median',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='slateplayerprojection',
            name='s75',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='slateplayerprojection',
            name='s90',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
