# Generated by Django 2.2 on 2022-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0173_auto_20220907_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='s20',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='slateplayerprojection',
            name='floor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Flr'),
        ),
    ]
