# Generated by Django 2.2 on 2022-09-12 07:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0175_slateplayer_csv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatelineup',
            name='sim_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
