# Generated by Django 2.2 on 2022-10-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0178_auto_20220914_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateProjectionImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_site', models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim')], default='4for4', max_length=255)),
                ('url', models.URLField()),
                ('weight', models.FloatField(default=0.0)),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_imports', to='nfl.Slate')),
            ],
        ),
    ]
