# Generated by Django 2.2 on 2022-10-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0180_auto_20221006_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateprojectionimport',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
