# Generated by Django 2.2 on 2022-10-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0181_slateprojectionimport_headers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slateprojectionimport',
            old_name='weight',
            new_name='ownership_weight',
        ),
        migrations.AddField(
            model_name='slateprojectionimport',
            name='projection_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
