# Generated by Django 2.2 on 2022-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0184_auto_20221007_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateprojectionimport',
            name='projection_sheet',
            field=models.FileField(blank=True, null=True, upload_to='uploads/projections'),
        ),
        migrations.AlterField(
            model_name='slateprojectionimport',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
