# Generated by Django 2.2 on 2022-10-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0186_sheetcolumnheaders_use_for_data_feed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetcolumnheaders',
            options={'ordering': ['projection_site'], 'verbose_name': 'Column Headers', 'verbose_name_plural': 'Column Headers'},
        ),
        migrations.AddField(
            model_name='winninglineup',
            name='rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='winninglineup',
            name='win_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
