# Generated by Django 2.2 on 2022-10-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0187_auto_20221012_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winninglineup',
            options={'ordering': ['-rating'], 'verbose_name': 'Lineup', 'verbose_name_plural': 'Lineups'},
        ),
        migrations.AddField(
            model_name='slateprojectionimport',
            name='field_lineup_count',
            field=models.IntegerField(default=50, verbose_name='# Field Lineups'),
        ),
    ]
