# Generated by Django 2.2 on 2022-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0188_auto_20221013_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetcolumnheaders',
            name='column_median_projection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sheetcolumnheaders',
            name='column_team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
