# Generated by Django 2.2 on 2022-10-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0189_auto_20221024_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='is_showdown',
            field=models.BooleanField(default=False),
        ),
    ]
