# Generated by Django 2.2 on 2022-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0190_slate_is_showdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProjections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_time', models.DateTimeField(auto_now_add=True)),
                ('json_data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='backtest',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='lineupconstructionrule',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='missingalias',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH'), ('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='playerselectioncriteria',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='sheetcolumnheaders',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='slate',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='slatebuildconfig',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='stackconstructionrule',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH')], default='fanduel', max_length=50),
        ),
    ]
