# Generated by Django 2.2 on 2022-10-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0191_auto_20221026_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketprojections',
            options={'verbose_name': 'Market Projections', 'verbose_name_plural': 'Market Projections'},
        ),
    ]
