# Generated by Django 2.2 on 2022-11-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0192_auto_20221026_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-start']},
        ),
        migrations.AddField(
            model_name='slateplayer',
            name='roster_position',
            field=models.CharField(default='FLEX', max_length=5),
        ),
        migrations.AlterField(
            model_name='missingalias',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH'), ('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='sheetcolumnheaders',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='4for4', max_length=255),
        ),
        migrations.AlterField(
            model_name='slateplayerownershipprojectionsheet',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='awesemo', max_length=255),
        ),
        migrations.AlterField(
            model_name='slateplayerrawprojection',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='4for4', max_length=255),
        ),
        migrations.AlterField(
            model_name='slateprojectionimport',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='4for4', max_length=255),
        ),
        migrations.AlterField(
            model_name='slateprojectionsheet',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='4for4', max_length=255),
        ),
    ]
