# Generated by Django 2.2 on 2022-11-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0193_auto_20221102_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateplayer',
            name='roster_position',
            field=models.CharField(choices=[('CPT', 'Captain'), ('MVP', 'MVP'), ('FLEX', 'Flex'), ('UTIL', 'Util')], default='FLEX', max_length=5),
        ),
    ]
