# Generated by Django 2.2 on 2022-11-03 14:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0194_auto_20221103_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingalias',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH'), ('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('etr_sd', 'Establish The Run DK Showdown'), ('etr_sg', 'Establish The Run FD Single Game'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='sheetcolumnheaders',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('etr_sd', 'Establish The Run DK Showdown'), ('etr_sg', 'Establish The Run FD Single Game'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='4for4', max_length=255),
        ),
        migrations.AlterField(
            model_name='slateplayerownershipprojectionsheet',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('etr_sd', 'Establish The Run DK Showdown'), ('etr_sg', 'Establish The Run FD Single Game'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='awesemo', max_length=255),
        ),
        migrations.AlterField(
            model_name='slateplayerrawprojection',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('etr_sd', 'Establish The Run DK Showdown'), ('etr_sg', 'Establish The Run FD Single Game'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='4for4', max_length=255),
        ),
        migrations.AlterField(
            model_name='slateprojectionimport',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('etr_sd', 'Establish The Run DK Showdown'), ('etr_sg', 'Establish The Run FD Single Game'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='4for4', max_length=255),
        ),
        migrations.AlterField(
            model_name='slateprojectionsheet',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('etr_sd', 'Establish The Run DK Showdown'), ('etr_sg', 'Establish The Run FD Single Game'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='4for4', max_length=255),
        ),
        migrations.CreateModel(
            name='SlateSDLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salary', models.IntegerField(default=0)),
                ('sim_scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('cpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpt', to='nfl.SlatePlayer')),
                ('flex1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex1', to='nfl.SlatePlayer')),
                ('flex2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex2', to='nfl.SlatePlayer')),
                ('flex3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex3', to='nfl.SlatePlayer')),
                ('flex4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex4', to='nfl.SlatePlayer')),
                ('flex5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flex5', to='nfl.SlatePlayer')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_sd_lineups', to='nfl.Slate')),
            ],
            options={
                'verbose_name': 'Slate SD Lineup',
                'verbose_name_plural': 'Slate SD Lineups',
                'ordering': ['-total_salary'],
            },
        ),
    ]
