# Generated by Django 2.2 on 2022-11-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0195_auto_20221103_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSDLineupToBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('median', models.FloatField(db_index=True, default=0.0)),
                ('s75', models.FloatField(db_index=True, default=0.0)),
                ('s90', models.FloatField(db_index=True, default=0.0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_sd_lineups_to_beat', to='nfl.FindWinnerBuild', verbose_name='Build')),
                ('slate_lineup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_sd_builds', to='nfl.SlateSDLineup', verbose_name='Lineup')),
            ],
            options={
                'verbose_name': 'Field SD Lineup',
                'verbose_name_plural': 'Field SD Lineups',
                'ordering': ['-median'],
            },
        ),
        migrations.CreateModel(
            name='WinningSDLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rate', models.FloatField(db_index=True, default=0.0)),
                ('win_count', models.IntegerField(db_index=True, default=0)),
                ('rating', models.FloatField(db_index=True, default=0.0)),
                ('median', models.FloatField(db_index=True, default=0.0)),
                ('s75', models.FloatField(db_index=True, default=0.0)),
                ('s90', models.FloatField(db_index=True, default=0.0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_sd_lineups', to='nfl.FindWinnerBuild', verbose_name='Build')),
                ('slate_lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_sd_builds', to='nfl.SlateSDLineup', verbose_name='Lineup')),
            ],
            options={
                'verbose_name': 'SD Lineup',
                'verbose_name_plural': 'SD Lineups',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='LineupSDMatchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rate', models.FloatField(db_index=True, default=0.0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd_matchups', to='nfl.FindWinnerBuild', verbose_name='Build')),
                ('field_lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd_matchups', to='nfl.FieldSDLineupToBeat')),
                ('slate_lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd_matchups', to='nfl.SlateSDLineup')),
            ],
            options={
                'verbose_name': 'SD Lineup Matchup',
                'verbose_name_plural': 'SD Lineup Matchups',
                'ordering': ['-win_rate'],
            },
        ),
    ]
