# Generated by Django 2.2 on 2022-11-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0196_fieldsdlineuptobeat_lineupsdmatchup_winningsdlineup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketprojections',
            name='json_data',
        ),
        migrations.AddField(
            model_name='marketprojections',
            name='content_type',
            field=models.CharField(choices=[('csv', 'csv'), ('json', 'json')], default='csv', max_length=5),
        ),
        migrations.AddField(
            model_name='marketprojections',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketprojections',
            name='projection_sheet',
            field=models.FileField(blank=True, null=True, upload_to='uploads/projections'),
        ),
        migrations.AddField(
            model_name='marketprojections',
            name='projection_site',
            field=models.CharField(choices=[('4for4', '4For4'), ('awesemo', 'Awesemo'), ('awesemo_own', 'Awesemo Ownership'), ('etr', 'Establish The Run'), ('etr_sd', 'Establish The Run DK Showdown'), ('etr_sg', 'Establish The Run FD Single Game'), ('tda', 'The Daily Average'), ('rg', 'Rotogrinders'), ('fc', 'Fantasy Cruncher'), ('rts', 'Run The Sims'), ('sabersim', 'Saber Sim'), ('labs', 'Fantasy Labs')], default='4for4', max_length=255),
        ),
        migrations.AddField(
            model_name='marketprojections',
            name='site',
            field=models.CharField(choices=[('draftkings', 'DK'), ('fanduel', 'FD'), ('yahoo', 'YH')], default='fanduel', max_length=50),
        ),
        migrations.AlterField(
            model_name='slateplayer',
            name='roster_position',
            field=models.CharField(choices=[('CPT', 'Captain'), ('MVP', 'MVP'), ('FLEX', 'Flex'), ('UTIL', 'Util'), ('QB', 'QB'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('DST', 'DST'), ('D', 'D'), ('DEF', 'DEF')], default='FLEX', max_length=5),
        ),
    ]
