# Generated by Django 2.2 on 2022-11-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0197_auto_20221111_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketprojections',
            name='content_type',
        ),
    ]
