# Generated by Django 2.2 on 2022-11-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0198_remove_marketprojections_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketprojections',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_projections', to='nfl.Week'),
        ),
    ]
