# Generated by Django 2.2 on 2022-12-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0204_auto_20221201_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findwinnerbuild',
            name='build_type',
            field=models.CharField(choices=[('h2h', 'Head-to-Head'), ('se', 'Single Entry')], default='h2h', max_length=10),
        ),
    ]
