# Generated by Django 2.2 on 2022-12-13 15:23

from django.db import migrations, models
import django.db.models.deletion
import nfl.models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0208_auto_20221209_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketprojections',
            name='week',
            field=models.ForeignKey(blank=True, default=nfl.models.Week.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_projections', to='nfl.Week'),
        ),
    ]
