version: '3.5'

services:
  db:
    container_name: lottery_production_db
    image: kartoza/postgis:12.1
    expose:
      - 5432
    environment:
      - POSTGRES_DB=lottery
      - POSTGRES_USER=lottery
      - POSTGRES_PASSWORD=lottery
    volumes:
      - ../data:/opt/data
      - ../postgres:/opt/postgres
      - lottery_db:/var/lib/postgresql
    networks:
      - lottery_network

  redis:
    container_name: lottery_production_redis
    image: redis:5.0
    command: redis-server
    volumes:
      - ../redis:/opt/redis
      - 'lottery_redis:/data'
    expose:
      - 6379
    networks:
      - lottery_network

  celery:
    container_name: lottery_production_celery
    build:
      context: ../django
    env_file:
      - production/django.env
    depends_on:
      - redis
    command: celery -A lottery worker -l info --concurrency=16 --prefetch-multiplier=1 --task-events 
    volumes:
      - ../django/lottery:/opt/lottery
      - lottery_static:/opt/static
      - lottery_media:/opt/media
    networks:
      - lottery_network
  
  flower:  
    image: mher/flower
    container_name: lottery_production_flower
    depends_on:
      - celery
    command: celery --broker=redis://redis:6379 flower --port=8888 --logging=DEBUG --url_prefix=flower
    expose:
      - 8888
    ports:  
      - 8888:8888
    volumes:
      - ../django/lottery:/opt/lottery
      - lottery_static:/opt/static
      - lottery_media:/opt/media
    networks:
      - lottery_network

  django:
    container_name: lottery_production_django
    build:
      context: ../django
    env_file:
      - production/django.env
    expose:
      - 8000
    depends_on:
      - db
      - redis
    volumes:
      - ../data:/opt/data
      - ../django/lottery:/opt/lottery
      - lottery_static:/opt/static
      - lottery_media:/opt/media
    command: /opt/lottery/startup/start-uwsgi.sh
    networks:
      - lottery_network

  nginx:
    container_name: lottery_production_nginx
    build:
      context: ../nginx
    env_file:
        - production/nginx.env
    links:
        - django
        - flower
    ports:
        - "80:80"
        - "443:443"
    depends_on:
        - django
    volumes:
        - /home/lottery/certs/:/etc/nginx/certs/
        - lottery_static:/opt/static
        - lottery_media:/opt/media
    restart: always
    command: nginx -g 'daemon off;'
    networks:
      - lottery_network

volumes:
  lottery_db:
    name: lottery_db
  lottery_redis:
    name: lottery_redis
  lottery_static:
    name: lottery_static
  lottery_media:
    name: lottery_media

networks:
  lottery_network:
    name: lottery