# Generated by Django 2.2 on 2022-01-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_auto_20220106_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlateMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slates', to='tennis.PinnacleMatch')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tennis.Slate')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MissingAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(choices=[('draftkings', 'DraftKings'), ('fanduel', 'Fanduel'), ('pinnacle', 'Pinnacle')], default='draftkings', max_length=50)),
                ('alias_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_1', to='tennis.Alias')),
                ('alias_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_2', to='tennis.Alias')),
                ('alias_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_3', to='tennis.Alias')),
            ],
            options={
                'verbose_name': 'Missing Alias',
                'verbose_name_plural': 'Missing Aliases',
            },
        ),
    ]
