# Generated by Django 2.2 on 2022-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0005_auto_20220110_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatematch',
            name='best_of',
            field=models.IntegerField(choices=[(3, '3'), (5, '5')], default=3),
        ),
    ]
