# Generated by Django 2.2 on 2022-01-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0007_slateplayerprojection_sim_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='slate_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='tennis.SlateMatch'),
        ),
    ]
