# Generated by Django 2.2 on 2022-01-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0010_slateplayerprojection_ceiling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_1', to='tennis.SlatePlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_2', to='tennis.SlatePlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='player_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_3', to='tennis.SlatePlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='player_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_4', to='tennis.SlatePlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='player_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_5', to='tennis.SlatePlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slatebuildlineup',
            name='player_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_as_player_6', to='tennis.SlatePlayerProjection'),
        ),
        migrations.AlterField(
            model_name='slateplayerprojection',
            name='ceiling',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Ceil'),
        ),
        migrations.DeleteModel(
            name='BuildPlayerProjection',
        ),
    ]
