# Generated by Django 2.2 on 2022-01-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0011_auto_20220111_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildconfig',
            name='optimize_by',
            field=models.CharField(choices=[('implied_win_pct', 'Implied Win %'), ('sim_win_pct', 'Simulated Win %'), ('median_projection', 'Median Projection'), ('ceiling_projection', 'Ceiling Projection')], default='implied_win_pct', max_length=50),
        ),
    ]
