# Generated by Django 2.2 on 2022-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0015_slatebuildconfig_clean_lineups_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatebuildlineup',
            name='implied_win_pct',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=10, verbose_name='iwin'),
        ),
        migrations.AddField(
            model_name='slatebuildlineup',
            name='sim_win_pct',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=10, verbose_name='sim_win'),
        ),
    ]
