# Generated by Django 2.2 on 2022-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0017_auto_20220111_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='entries',
            field=models.FileField(blank=True, null=True, upload_to='uploads/entries'),
        ),
    ]
