# Generated by Django 2.2 on 2022-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0018_slate_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='in_play',
            field=models.BooleanField(default=True),
        ),
    ]
