# Generated by Django 2.2 on 2022-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0019_slateplayerprojection_in_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='max_exposure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
