# Generated by Django 2.2 on 2022-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0022_auto_20220120_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slate',
            name='target_scores',
        ),
        migrations.RemoveField(
            model_name='slate',
            name='top_scores',
        ),
        migrations.AddField(
            model_name='slate',
            name='target_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Target'),
        ),
        migrations.AddField(
            model_name='slate',
            name='top_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Top'),
        ),
    ]
