# Generated by Django 2.2 on 2022-01-20 14:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0023_auto_20220120_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='w_sim_scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=None),
        ),
    ]
