# Generated by Django 2.2 on 2022-01-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0024_slateplayerprojection_w_sim_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='min_exposure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
