# Generated by Django 2.2 on 2022-01-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0025_slateplayerprojection_min_exposure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateplayerprojection',
            name='max_exposure',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
