# Generated by Django 2.2 on 2022-01-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0026_auto_20220120_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slateplayerprojection',
            name='max_exposure',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='max'),
        ),
        migrations.AlterField(
            model_name='slateplayerprojection',
            name='min_exposure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='min'),
        ),
    ]
