# Generated by Django 2.2 on 2022-02-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0027_auto_20220124_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='ace_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='slateplayerprojection',
            name='df_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='slateplayerprojection',
            name='spw_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
