# Generated by Django 2.2 on 2022-02-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0029_slateplayerprojection_rpw_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='slateplayerprojection',
            name='optimal_exposure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='opt'),
        ),
    ]
