# Generated by Django 2.2 on 2022-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0030_slateplayerprojection_optimal_exposure'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinRateLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implied_odds', models.FloatField(default=0.0)),
                ('wta_odds', models.FloatField(default=0.0)),
                ('wta_ss_odds', models.FloatField(default=0.0)),
                ('atp3_odds', models.FloatField(default=0.0)),
                ('atp3_ss_odds', models.FloatField(default=0.0)),
                ('atp5_odds', models.FloatField(default=0.0)),
                ('atp5_ss_odds', models.FloatField(default=0.0)),
            ],
        ),
    ]
