# Generated by Django 2.2 on 2022-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0031_winratelookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sim_input_files'),
        ),
    ]
