# Generated by Django 2.2 on 2023-01-12 14:38

from django.db import migrations

def generate_player_ids(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Player = apps.get_model('tennis', 'Player')
    for player in Player.objects.all():
        player.player_id = f'{player.tour}-{player.player_id}'
        player.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0033_auto_20230112_1438'),
    ]

    operations = [
        migrations.RunPython(generate_player_ids),
    ]
