# Generated by Django 2.2 on 2023-01-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0034_auto_20230112_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
