# Generated by Django 2.2 on 2023-01-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0035_auto_20230112_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.CharField(blank=True, choices=[('r', 'R'), ('l', 'L'), ('u', 'U')], max_length=1, null=True),
        ),
    ]
