# Generated by Django 2.2 on 2023-01-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0037_auto_20230112_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RankingHistory',
        ),
    ]
