# Generated by Django 2.2 on 2023-01-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0038_delete_rankinghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
