# Generated by Django 2.2 on 2023-01-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0039_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourney_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tourney_name', models.CharField(blank=True, max_length=255, null=True)),
                ('surface', models.CharField(blank=True, max_length=255, null=True)),
                ('draw_size', models.IntegerField(blank=True, null=True)),
                ('tourney_level', models.CharField(blank=True, max_length=255, null=True)),
                ('tourney_date', models.DateField(blank=True, null=True)),
                ('match_num', models.IntegerField(blank=True, null=True)),
                ('winner_seed', models.CharField(blank=True, max_length=255, null=True)),
                ('winner_entry', models.CharField(blank=True, max_length=255, null=True)),
                ('winner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('winner_hand', models.CharField(blank=True, max_length=255, null=True)),
                ('winner_ht', models.IntegerField(blank=True, null=True)),
                ('winner_ioc', models.CharField(blank=True, max_length=255, null=True)),
                ('winner_age', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('loser_seed', models.CharField(blank=True, max_length=255, null=True)),
                ('loser_entry', models.CharField(blank=True, max_length=255, null=True)),
                ('loser_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loser_hand', models.CharField(blank=True, max_length=255, null=True)),
                ('loser_ht', models.IntegerField(blank=True, null=True)),
                ('loser_ioc', models.CharField(blank=True, max_length=255, null=True)),
                ('loser_age', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('best_of', models.IntegerField(blank=True, null=True)),
                ('round', models.CharField(blank=True, max_length=255, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('w_ace', models.IntegerField(blank=True, null=True)),
                ('w_df', models.IntegerField(blank=True, null=True)),
                ('w_svpt', models.IntegerField(blank=True, null=True)),
                ('w_1stIn', models.IntegerField(blank=True, null=True)),
                ('w_1stWon', models.IntegerField(blank=True, null=True)),
                ('w_2ndWon', models.IntegerField(blank=True, null=True)),
                ('w_SvGms', models.IntegerField(blank=True, null=True)),
                ('w_bpSaved', models.IntegerField(blank=True, null=True)),
                ('w_bpFaced', models.IntegerField(blank=True, null=True)),
                ('l_ace', models.IntegerField(blank=True, null=True)),
                ('l_df', models.IntegerField(blank=True, null=True)),
                ('l_svpt', models.IntegerField(blank=True, null=True)),
                ('l_1stIn', models.IntegerField(blank=True, null=True)),
                ('l_1stWon', models.IntegerField(blank=True, null=True)),
                ('l_2ndWon', models.IntegerField(blank=True, null=True)),
                ('l_SvGms', models.IntegerField(blank=True, null=True)),
                ('l_bpSaved', models.IntegerField(blank=True, null=True)),
                ('l_bpFaced', models.IntegerField(blank=True, null=True)),
                ('winner_rank', models.IntegerField(blank=True, null=True)),
                ('winner_rank_points', models.IntegerField(blank=True, null=True)),
                ('loser_rank', models.IntegerField(blank=True, null=True)),
                ('loser_rank_points', models.IntegerField(blank=True, null=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losing_matches', to='tennis.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_matches', to='tennis.Player')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
