# Generated by Django 2.2 on 2023-01-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0042_auto_20230117_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnaclematch',
            name='away_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_odds_as_away', to='tennis.Player'),
        ),
        migrations.AddField(
            model_name='pinnaclematch',
            name='home_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_odds_as_home', to='tennis.Player'),
        ),
    ]
