# Generated by Django 2.2 on 2023-01-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0044_remove_alias_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='tennis.Player'),
        ),
    ]
