# Generated by Django 2.2 on 2023-01-18 14:38
import difflib
import pandas
import sqlalchemy

from django.conf import settings
from django.db import migrations


def add_player_to_alias(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Alias = apps.get_model('tennis', 'Alias')
    Player = apps.get_model('tennis', 'Player')

    df_player = pandas.DataFrame.from_records(Player.objects.all().values('player_id', 'first_name', 'last_name'))
    df_player['dk_name'] = df_player.apply(lambda x: f'{x.first_name} {x.last_name}', axis=1)
    df_player['fd_name'] = df_player.apply(lambda x: f'{x.first_name} {x.last_name}', axis=1)
    df_player['pinn_name'] = df_player.apply(lambda x: f'{x.first_name} {x.last_name}', axis=1)
    df_player.drop([
        'first_name',
        'last_name'
    ], axis=1, inplace=True)

    print(df_player)

    user = settings.DATABASES['default']['USER']
    password = settings.DATABASES['default']['PASSWORD']
    database_name = settings.DATABASES['default']['NAME']
    database_url = 'postgresql://{user}:{password}@db:5432/{database_name}'.format(
        user=user,
        password=password,
        database_name=database_name,
    )

    engine = sqlalchemy.create_engine(database_url, echo=False)
    df_player.to_sql('tennis_alias', engine, if_exists='append', index=False, chunksize=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0045_alias_player'),
    ]

    operations = [
        migrations.RunPython(add_player_to_alias),
    ]
