# Generated by Django 2.2 on 2023-01-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0046_auto_20230118_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinnaclematch',
            old_name='event',
            new_name='tournament_name',
        ),
    ]
