# Generated by Django 2.2 on 2023-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0047_auto_20230120_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnaclematchodds',
            name='away_spread',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pinnaclematchodds',
            name='home_spread',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
