# Generated by Django 2.2 on 2021-11-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draftkings_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fanduel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('yahoo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('draftkings_player_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fanduel_player_id', models.CharField(blank=True, max_length=255, null=True)),
                ('yahoo_player_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.PositiveIntegerField(default=1, verbose_name='Week #')),
                ('slate_year', models.PositiveIntegerField(default=2021)),
                ('sim_type', models.CharField(choices=[('rts', 'Run The Sims'), ('ben', 'Ben'), ('greatleaf', 'GreatLeaf')], default='rts', max_length=15)),
                ('player_outcomes', models.FileField(blank=True, null=True, upload_to='uploads/sims')),
            ],
            options={
                'ordering': ['-slate_year', '-week_num'],
            },
        ),
    ]
