# Generated by Django 2.2 on 2021-12-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(max_length=64)),
                ('slate_week', models.PositiveIntegerField(default=0, verbose_name='Week #')),
                ('slate_year', models.PositiveIntegerField(default=0)),
                ('is_main_slate', models.BooleanField(default=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('contest_json', models.TextField(blank=True, null=True)),
                ('last_page_processed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContestPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rank', models.IntegerField(default=1)),
                ('max_rank', models.IntegerField(default=1)),
                ('prize', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='yahoo.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_json', models.TextField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='yahoo.Contest')),
            ],
        ),
    ]
